Repository sagemathinc/cocalc, pull requests merged in 2018-05, with the labels that each got.

#2861 sagews: disable require.ensure for d3 (plotting graphs)
  src/smc-webapp/sagews/sagews.coffee
Labels: in progress

#2864 Issue/2862
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/sage_server.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
Labels: PR-needs review

#2869 Enable support for "from __future__ import ..." in sage worksheets
  src/smc_sagews/smc_sagews/sage_parsing.py
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/sage_server.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
Labels: PR-positive review

#2871 sagews2pdf: changing default encoding of strings to address special chars in date and author strings
  src/smc_pyutil/smc_pyutil/sagews2pdf.py
Labels: PR-positive review

#2887 matplotlib backend selection in salvus server
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/sage_server.py
Labels: PR-positive review

#2893 webapp: simple workaround to unmangle katex formulas in RTL contexts
  src/smc-webapp/index.sass
Labels: PR-needs review

#2899 static/landingpage: show warning to firefox users about issue #2875
  src/webapp-lib/index.pug
Labels: PR-needs review

#2907 Issue/2906
  src/smc-webapp/jupyter/cell-output-message.cjsx
Labels: PR-needs review
