Repository sagemathinc/cocalc, pull requests merged in 2018-04, with the labels that each got.

#2803 make "something bad" message more useful
  src/webapp-lib/app.pug
Labels: A-frontend, PR-needs review

#2792 db: add projects.compute_image field to specify which one to run in kucalc
  src/smc-util/db-schema.coffee
Labels: PR-positive review

#2809 webapp: process links should also fix <video> tags
  src/smc-webapp/process-links.coffee
Labels: PR-needs review

#2811 Fix hidden send button on thin screens
  src/smc-webapp/smc_chat.cjsx
Labels: PR-needs review

#2813 webapp install: strategically calling git to initialize submodules
  src/dev/project/start_webpack.py
  src/install.py
  src/scripts/smc-install-all
Labels: PR-needs review

#2825 webapp/misc: html sanitization stumbles over undefined "this"
  src/smc-util/misc.coffee
Labels: PR-needs review, in progress

#2818 webapp: improve error message display
  src/smc-webapp/editor.coffee
Labels: PR-needs review

#2827 webapp/landingpage: small changes to the trial info box
  src/smc-webapp/customize.cjsx
  src/smc-webapp/landing_page.cjsx
Labels: in progress

#2831 sagews: skip init_hide_show_gutter for undefined codemirrors
  src/smc-webapp/sagews/sagews.coffee
Labels: PR-needs review, in progress

#2838 webapp: fix/adjust new icon set for sagews %md
  src/smc-webapp/buttonbar.coffee
  src/smc-webapp/code-editor/frame-title-bar.cjsx
  src/smc-webapp/editor.coffee
  src/smc-webapp/editor.html
Labels: PR-needs review, in progress

#2841 hub/kucalc: expose total idle timeout as part of the quota -- used for scheduling on nodes
  src/smc-hub/kucalc/quota.coffee
Labels: in progress

#2850 Issue/2124
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-needs review
