Repository sagemathinc/cocalc, pull requests merged in 2018-12, with the labels that each got.

#3392 webapp/terminal: fixing hidden scrollbar
  src/smc-webapp/frame-editors/terminal-editor/actions.ts
  src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts
  src/smc-webapp/frame-editors/terminal-editor/terminal-manager.ts
  src/smc-webapp/frame-editors/terminal-editor/terminal.tsx
  src/smc-webapp/index.sass
Labels: PR-needs review

#3395 x11: more apps and space around buttons
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-needs review

#3396 webapp/x11: sort launcher by labels and add two more
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-needs review

#3399 webapp: fix terminal help url
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/terminal-editor/actions.ts
Labels: PR-needs review

#3388 Add signup question
  src/smc-hub/create-account.coffee
  src/smc-hub/postgres-server-queries.coffee
  src/smc-util/client.coffee
  src/smc-util/db-schema.coffee
  src/smc-util/message.coffee
  src/smc-webapp/redux_account.coffee
  src/smc-webapp/sign-up.tsx
Labels: PR-positive review

#3404 webapp/desktop: basically fixing the new files notification box
  src/smc-webapp/desktop_app.cjsx
Labels: PR-needs review

#3330 [RFC] Upgrade Typescript
  src/package.json
  src/smc-webapp/course/upgrades.tsx
  src/smc-webapp/frame-editors/latex-editor/mouse-click.ts
  src/smc-webapp/frame-editors/latex-editor/mouse-draggable.ts
  src/smc-webapp/frame-editors/latex-editor/pdfjs.tsx
  src/smc-webapp/jupyter/javascript-eval.ts
  src/smc-webapp/smc_chat.tsx
Labels: PR-needs review

#3376 hub/quota: test, maximum, refactoring, ...
  src/scripts/postgresql/cool-queries.md
  src/smc-hub/kucalc/quota.coffee
  src/smc-hub/test/kucalc/init.coffee
  src/smc-hub/test/kucalc/quota.coffee
Labels: PR-needs review

#3414 webapp/latex: fix #3413
  src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
Labels: P-high, PR-needs review

#3422 firefox connection issue: 65 beta4 exhibits symptoms similar to #2875
  src/webapp-lib/preflight-checks.ts
Labels: PR-needs review

#3417 add ts support to hub api mocha test
  .travis-test.sh
  src/smc-hub/package.json
  src/smc-hub/test/api/copy_between_projects.coffee
Labels: PR-needs review
