Repository sagemathinc/cocalc, pull requests merged in 2018-08, with the labels that each got.

#3015 Issue/2510 1
  src/smc-util/upgrade-spec.coffee
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/r_account.cjsx
  src/smc-webapp/widget-ssh-keys/main.cjsx
Labels: PR-needs review

#3022 support for .Rtex files, generalizing what was done for .Rnw
  src/smc-webapp/file-associations.coffee
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/clean.ts
  src/smc-webapp/frame-editors/latex-editor/knitr.ts
  src/smc-webapp/frame-editors/latex-editor/register.ts
  src/smc-webapp/frame-editors/latex-editor/util.ts
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/project_store.ts
  src/smc_pyutil/smc_pyutil/templates/linux/default.rtex
Labels: PR-needs review

#3028 use syncdb file and store correctly
  src/smc-webapp/frame-editors/latex-editor/build-command.tsx
Labels: PR-needs review

#3032 spellcheck special cases for rtex/rnw files
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/code-editor/spell-check.ts
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/register.ts
  src/smc-webapp/frame-editors/latex-editor/util.ts
Labels: PR-needs review

#3031 webapp/code editor spellcheck: canonicalize filename extension to select correct mode
  src/smc-webapp/frame-editors/code-editor/spell-check.ts
Labels: PR-needs review

#3038 initial fix
  src/smc-util/misc.coffee
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_search.cjsx
Labels: PR-needs review

#3036 Issue/2510 2
  src/smc-webapp/admin/account-creation-token.tsx
  src/smc-webapp/admin/stripe-user.tsx
  src/smc-webapp/admin/system-notifications.tsx
  src/smc-webapp/api-key.cjsx
  src/smc-webapp/billing.cjsx
  src/smc-webapp/collaborators/add-to-project.cjsx
  src/smc-webapp/editor_pdf.cjsx
  src/smc-webapp/file_use.cjsx
  src/smc-webapp/frame-editors/markdown-editor/experiments/insert-link.cjsx
  src/smc-webapp/landing_page.cjsx
  src/smc-webapp/library.cjsx
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/project_new.cjsx
  src/smc-webapp/project_search.cjsx
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/projects.cjsx
  src/smc-webapp/projects/create-project.cjsx
  src/smc-webapp/r_account.cjsx
  src/smc-webapp/r_misc.cjsx
  src/smc-webapp/r_upgrades.cjsx
  src/smc-webapp/tasks/empty-trash.cjsx
  src/smc-webapp/tasks/list.cjsx
  src/smc-webapp/widget-ssh-keys/main.cjsx
Labels: PR-needs work

#3051 webapp file breakcrumb history: fix erroneous detection of subdirectory if dir names are similar
  src/smc-webapp/project_actions.ts
Labels: PR-needs review

#3052 Issue/369
  src/smc_sagews/smc_sagews/sage_server.py
  src/smc_sagews/smc_sagews/tests/a-init.sage
  src/smc_sagews/smc_sagews/tests/conftest.py
  src/smc_sagews/smc_sagews/tests/test_00_timing.py
  src/smc_sagews/smc_sagews/tests/test_env.py
  src/smc_sagews/smc_sagews/tests/test_graphics.py
  src/smc_sagews/smc_sagews/tests/test_unicode.py
Labels: PR-needs review

#3053 webapp/jupyter: fix completion after pressing a key
  src/smc-webapp/jupyter/actions.ts
Labels: PR-needs review

#3060 Issue/3056
  src/smc_sagews/smc_sagews/sage_server.py
  src/smc_sagews/smc_sagews/tests/a-init.sage
  src/smc_sagews/smc_sagews/tests/conftest.py
  src/smc_sagews/smc_sagews/tests/sage_init_files/define_var.sage
  src/smc_sagews/smc_sagews/tests/sage_init_files/runtime_err.sage
  src/smc_sagews/smc_sagews/tests/sage_init_files/syntax_err.sage
  src/smc_sagews/smc_sagews/tests/test_env.py
Labels: PR-needs review

#3063 Persist grading
  src/smc-webapp/course/actions.ts
  src/smc-webapp/course/assignments_panel.tsx
  src/smc-webapp/course/common.tsx
  src/smc-webapp/course/main.tsx
  src/smc-webapp/course/store.ts
  src/smc-webapp/course/students_panel.tsx
  src/smc-webapp/course/util.ts
  src/smc-webapp/widget-markdown-input/main.tsx
Labels: PR-needs review

#3064 Show add subscription for first time customers
  src/smc-webapp/billing.cjsx
Labels: PR-needs review

#3065 webapp: hide labels of some tabs when there are many open projects
  src/smc-webapp/app_shared.cjsx
  src/smc-webapp/desktop_app.cjsx
Labels: PR-needs review

#3075 consistent icons
  src/smc-webapp/project_settings.cjsx
Labels: PR-needs review

#3067 Course typing
  src/smc-webapp/app-framework/TypedMap.ts
  src/smc-webapp/app-framework/examples/example_TypedMap.ts
  src/smc-webapp/course/assignments_panel.tsx
  src/smc-webapp/course/store.ts
Labels: PR-needs review

#3080 explicit void return types
  src/smc-webapp/jupyter/actions.ts
Labels: PR-positive review

#3079 improve key for caching connected components
  src/smc-webapp/app-framework.ts
Labels: PR-needs review

#3033 UI selector to choose underlying project image
  src/smc-hub/postgres-server-queries.coffee
  src/smc-util/compute-images.coffee
  src/smc-util/db-schema.coffee
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_settings.cjsx
Labels: PR-needs work

#3088 jupyter/hub: add 3x `declare const $: any;` to make the hub start again
  src/smc-webapp/jupyter/cell-input.tsx
  src/smc-webapp/jupyter/cell-list.tsx
  src/smc-webapp/jupyter/cell-output-message.tsx
Labels: PR-needs review

#3087 remove host info from project settings
  src/smc-webapp/project_settings.cjsx
Labels: PR-needs review

#3086 cleaned up some typescript files
  src/smc-webapp/jupyter/codemirror-editor.tsx
  src/smc-webapp/jupyter/output-handler.ts
Labels: PR-needs review

#3085 Issue/3083
  src/smc-webapp/_examples.sass
  src/smc-webapp/assistant/body.cjsx
Labels: PR-needs review

#3090 Issue/3083 part 2
  src/smc-webapp/_examples.sass
  src/smc-webapp/assistant/body.cjsx
Labels: PR-needs review

#3093 jupyter2/project:
  src/smc-project/jupyter/execute-code.ts
  src/smc-webapp/jupyter/output-handler.ts
  src/smc-webapp/jupyter/project-actions.ts
Labels: PR-needs review

#3091 adding custom global type defs for cocalc
  src/globals.d.ts
  src/smc-project/globals.d.ts
  src/smc-project/package.json
  src/smc-webapp/jupyter/actions.ts
  src/smc-webapp/jupyter/cell-input.tsx
  src/smc-webapp/jupyter/cell-list.tsx
  src/smc-webapp/jupyter/cell-output-message.tsx
  src/smc-webapp/jupyter/server-urls.ts
  src/smc-webapp/jupyter/store.ts
Labels: PR-needs work

#3100 debounce collaborator search queries
  src/smc-webapp/collaborators/new-collabs.tsx
Labels: PR-work in progress

#3106 highlight and select collaborators by clicking
  src/smc-webapp/collaborators/new-collabs.tsx
  src/smc-webapp/collaborators/picker-list.tsx
Labels: PR-needs review

#3112 Issue/3104
  src/smc_sagews/smc_sagews/sage_jupyter.py
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/sage_server.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-needs review

#3137 minor edits by Hal
  src/webapp-lib/doc/r-statistical-software.pug
Labels: PR-needs review

#3136 webapp/projects: add explicit note about deleting/removing sensitive data
  src/smc-webapp/project_settings.cjsx
Labels: PR-needs review

#3117 latex: fix #3111 edge case
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/build-command.tsx
Labels: PR-needs review

#3142 do not randomize data image urls
  src/smc-webapp/misc_page.coffee
Labels: PR-needs review
