Repository sagemathinc/cocalc, pull requests merged in 2019-01, with the labels that each got.

#3426 webapp: rust .rs files + an icon that looks a bit like the rust logo
  src/smc-webapp/file-associations.coffee
Labels: PR-easy, PR-needs review

#3431 update prettier to be in sync with system-wide version
  src/package.json
  src/smc-project/package.json
Labels: PR-easy, PR-needs review

#3418 webapp/x11: QGIS, DS9, Octave, Maxima, Xcas and System Monitor
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-easy, PR-positive review

#3443 webapp: account for cleared state in ProjectRow
  src/smc-webapp/projects/project-row.tsx
Labels: PR-easy, PR-needs review

#3445 webapp preflight: remove ff 65 warning
  src/webapp-lib/preflight-checks.ts
Labels: PR-easy, PR-needs review

#3444 x11: help moved to new location and Gedit launcher
  src/smc-webapp/frame-editors/x11-editor/actions.ts
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
  src/webapp-lib/doc/x11.pug
Labels: PR-easy, PR-needs review

#3441 webapp/project actions: path in close_tab is not always defined -- #3440
  src/smc-webapp/project_actions.ts
Labels: PR-easy, PR-needs review

#3428 x11: add sqlitebrowser
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-easy, PR-needs review

#3411 hub/test: fix some timestamp jitter
  src/smc-hub/test/postgres/postgres-user-queries-syncstring.coffee
Labels: PR-easy, PR-needs review

#3429 Project uptime string
  src/smc-util/misc.js
  src/smc-util/test/misc-test.coffee
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/r_misc/index.cjsx
  src/smc-webapp/r_misc/time-elapsed.tsx
Labels: PR-easy, PR-kucalc, PR-needs review

#3467 webapp/project log: fix sorting of log entries, especially when searching
  src/smc-webapp/project_log.cjsx
Labels: PR-easy, PR-needs review

#3460 software: adding stable-2019-01-12 and tweaking descriptions a little bit
  src/smc-util/compute-images.coffee
Labels: PR-easy, PR-needs review

#3416 webapp/x11: 100, 125 and 150% and 200% zoom selections
  src/smc-webapp/frame-editors/_style.sass
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/frame-tree/format-bar.tsx
  src/smc-webapp/frame-editors/frame-tree/frame-tree.tsx
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
  src/smc-webapp/frame-editors/x11-editor/actions.ts
  src/smc-webapp/frame-editors/x11-editor/editor.ts
  src/smc-webapp/index.sass
Labels: PR-careful, PR-needs work, PR-positive review

#3372 Add persistence to user search in admin page
  src/smc-webapp/admin/actions.ts
  src/smc-webapp/admin/index.ts
  src/smc-webapp/admin/init.ts
  src/smc-webapp/admin/page.tsx
  src/smc-webapp/admin/store.ts
  src/smc-webapp/admin/users/user-search.tsx
  src/smc-webapp/app-framework.ts
  src/smc-webapp/app_shared.cjsx
Labels: PR-positive review

#3478 webapp/pdfjs: show page number between pages again
  src/smc-webapp/frame-editors/latex-editor/pdfjs-page.tsx
Labels: PR-easy, PR-needs review

#3491 webapp/latex: 4 min timeout latexmk
  src/smc-webapp/frame-editors/latex-editor/latexmk.ts
Labels: A-LaTeX, PR-easy, PR-needs review

#3489 npm: update prettier
  src/package.json
  src/smc-project/package.json
Labels: PR-easy, PR-needs review

#3500 have projects_all example query in api doc
  src/smc-util/message.coffee
Labels: A-API, PR-needs review

#3488 webapp/latex: fix knitr error line in gutter
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/knitr.ts
Labels: PR-easy, PR-positive review

#3498 webapp/landing: doc page is more informative than landing page
  src/smc-webapp/landing_page.cjsx
Labels: PR-easy, PR-needs review

#3481 webapp/x11: add cadabra2
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-easy, PR-needs review

#3477 sync (mostly): fix a couple of ineffective typings
  src/smc-project/sync/server.ts
  src/smc-util/sync/editor/db/sync.ts
  src/smc-util/sync/editor/generic/sync-doc.ts
  src/smc-util/sync/table/synctable.ts
  src/smc-webapp/stopwatch/stopwatch.tsx
Labels: PR-dangerous, PR-needs review

#3476 webapp: adding rel="noopener" to external links
  src/smc-webapp/account_ssh_keys.cjsx
  src/smc-webapp/api-key.cjsx
  src/smc-webapp/assistant/body.cjsx
  src/smc-webapp/assistant/footer.cjsx
  src/smc-webapp/billing.cjsx
  src/smc-webapp/compute_environment.cjsx
  src/smc-webapp/course/help_box.tsx
  src/smc-webapp/course/students_panel.tsx
  src/smc-webapp/editor_archive.cjsx
  src/smc-webapp/editor_git.cjsx
  src/smc-webapp/editor_jupyter.coffee
  src/smc-webapp/editor_pdf.cjsx
  src/smc-webapp/jupyter/about.tsx
  src/smc-webapp/jupyter/nbconvert.tsx
  src/smc-webapp/library.cjsx
  src/smc-webapp/misc_page.coffee
  src/smc-webapp/process-links.coffee
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/r_help.cjsx
  src/smc-webapp/r_misc/index.cjsx
  src/smc-webapp/r_profile_image.tsx
  src/smc-webapp/r_upgrades.cjsx
  src/smc-webapp/side_chat.cjsx
  src/smc-webapp/support.cjsx
  src/webapp-lib/app.pug
  src/webapp-lib/doc/r-statistical-software.pug
  src/webapp-lib/index.pug
  src/webapp-lib/policies/copyright.pug
  src/webapp-lib/policies/index.pug
  src/webapp-lib/policies/pricing.pug
  src/webapp-lib/policies/privacy.pug
  src/webapp-lib/policies/terms.pug
  src/webapp-lib/preflight-checks.ts
Labels: PR-needs review

#3408 hub/kucalc: typescript quota function
  src/smc-hub/kucalc/quota.coffee
  src/smc-hub/kucalc/quota.ts
  src/smc-hub/test/kucalc/compute-client.coffee
  src/smc-hub/test/kucalc/quota.coffee
Labels: PR-careful, PR-needs review

#3486 webapp/share: fix updating info about listing & description
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_files.cjsx
Labels: PR-easy, PR-needs review

#3435 january 2019 npm update
  src/package.json
  src/smc-hub/package.json
  src/smc-project/package.json
  src/smc-util-node/package.json
  src/smc-util/package.json
  src/smc-webapp/jupyter/package.json
  src/smc-webapp/package.json
  src/webapp-lib/primus/update_primus.coffee
Labels: P-high, PR-careful, PR-positive review

#3508 open_new_tab emulates rel=noopener by removing the opener attribute
  src/smc-webapp/misc_page.coffee
Labels: PR-work in progress

#3513 webapp/jupyter classical: fix title offset
  src/smc-webapp/editor_jupyter.coffee
Labels: PR-easy, PR-needs review

#3510 webapp: codemirror "edit_selection" use open_new_tab function
  src/smc-webapp/misc_page.coffee
Labels: PR-easy, PR-needs review

#3518 project/memory calc: no need to add rss_huge, and total_cache.
  src/smc-project/kucalc.coffee
Labels: PR-needs review

#3524 minor updates to sagews pytest and api mocha
  src/smc-hub/package.json
  src/smc-hub/test/api/text_files.coffee
  src/smc_sagews/smc_sagews/tests/test_sagews.py
Labels: PR-needs review

#3525 webapp: improve info text for select-file actions
  src/smc-webapp/project_files.cjsx
Labels: PR-easy, PR-needs review

#3523 Track various user interactions via Google Analytics
  src/smc-webapp/app_shared.cjsx
  src/smc-webapp/chat-indicator.cjsx
  src/smc-webapp/project/file-tab.cjsx
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/projects/create-project.tsx
  src/smc-webapp/projects/project-row.tsx
  src/smc-webapp/projects_nav.cjsx
  src/smc-webapp/tracker/index.ts
Labels: PR-easy, PR-needs review
