Repository sagemathinc/cocalc, pull requests merged in 2019-05, with the labels that each got.

#3777 NPM package update april 2019
  src/package-lock.json
  src/package.json
  src/scripts/smc-install-all
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/smc-util-node/package-lock.json
  src/smc-util/package-lock.json
  src/smc-util/package.json
  src/smc-webapp/frame-editors/latex-editor/pdfjs-doc-cache.ts
  src/smc-webapp/jquery-plugins/katex.ts
  src/smc-webapp/jupyter/package-lock.json
  src/smc-webapp/jupyter/package.json
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#3795 travis: pip-install missing python packages
  .travis-test.sh
  .travis.yml
  src/install.py
  src/webapp-lib/term/color_themes.js
  src/webapp-lib/term/compile
Labels: PR-needs review

#3800 quota: mixup cpu shared vs dedicated
  src/smc-hub/test/kucalc/quota.coffee
  src/smc-util/upgrade-spec.js
Labels: PR-easy, PR-needs review

#3807 webapp: comment out console line in user-tracking
  src/smc-webapp/user-tracking.ts
Labels: PR-easy, PR-needs review

#3814 share: add audio file support
  src/smc-webapp/share/extensions.coffee
  src/smc-webapp/share/public-path.cjsx
Labels: E-easy, PR-needs review

#3808 wrap local storage for session save/restore
  src/smc-webapp/misc/local-storage.ts
  src/smc-webapp/session.ts
Labels: PR-needs review

#3818 webapp: erlang files in codemirror
  src/smc-webapp/file-associations.ts
Labels: E-easy, PR-needs review

#3820 update katex 0.10.2
  src/package.json
  src/smc-webapp/frame-editors/frame-tree/print.ts
  src/smc-webapp/package.json
  src/smc-webapp/share/page.cjsx
  src/webapp-lib/_inc_head.pug
Labels: PR-easy, PR-needs review

#3825 hub/api: require valid api key and not-banned account for all calls
  src/smc-hub/api/handler.coffee
  src/smc-hub/test/api/apikey.coffee
Labels: PR-easy, PR-needs review

#3833 project/formatter: node 10 fallout regarding fs.unlink
  src/smc-project/formatters/bib-format.ts
  src/smc-project/formatters/clang-format.ts
  src/smc-project/formatters/gofmt.ts
  src/smc-project/formatters/html-format.ts
  src/smc-project/formatters/latex-format.ts
  src/smc-project/formatters/python-format.ts
  src/smc-project/formatters/r-format.ts
  src/smc-project/formatters/xml-format.ts
Labels: PR-easy, PR-needs review

#3828 Block URLs in names
  src/smc-hub/client/create-account.ts
  src/smc-hub/postgres-server-queries.coffee
  src/smc-util/misc2.ts
  src/smc-util/test/misc-test.coffee
  src/smc-webapp/landing-page/sign-up.tsx
Labels: PR-easy, PR-needs work

#3836 misc/validate name: harden URL detection
  src/smc-util/misc2.ts
  src/smc-util/package.json
  src/smc-util/test/misc-test.coffee
Labels: PR-needs review

#3840 static page improvements
  src/webapp-lib/_base.pug
  src/webapp-lib/doc/_style.sass
  src/webapp-lib/doc/features.pug
  src/webapp-lib/doc/index.pug
  src/webapp-lib/doc/jupyter-notebook.pug
  src/webapp-lib/doc/latex-editor.pug
  src/webapp-lib/doc/linux-terminal.pug
  src/webapp-lib/doc/python.pug
  src/webapp-lib/doc/r-statistical-software.pug
  src/webapp-lib/doc/software-executables.pug
  src/webapp-lib/doc/x11.pug
Labels: PR-easy, PR-needs review

#3845 Add disable mentions account option
  src/smc-util/db-schema.js
  src/smc-webapp/chat/actions.coffee
  src/smc-webapp/chat/input.tsx
  src/smc-webapp/r_account.cjsx
  src/smc-webapp/side_chat.cjsx
  src/smc-webapp/smc_chat.tsx
Labels: PR-needs review

#3859 static/landing: couple of small changes
  src/webapp-lib/_base.pug
  src/webapp-lib/assets/cocalc-pythontex.png
  src/webapp-lib/assets/jupyter-logo.svg
  src/webapp-lib/assets/latex-logo.svg
  src/webapp-lib/assets/linux-logo.svg
  src/webapp-lib/assets/python-logo.svg
  src/webapp-lib/assets/x11-logo.svg
  src/webapp-lib/doc/_style.sass
  src/webapp-lib/doc/features.pug
  src/webapp-lib/doc/jupyter-notebook.pug
  src/webapp-lib/doc/latex-editor.pug
  src/webapp-lib/doc/linux-terminal.pug
  src/webapp-lib/doc/python.pug
  src/webapp-lib/doc/r-statistical-software.pug
  src/webapp-lib/doc/x11.pug
  src/webapp-lib/index.pug
Labels: PR-needs review

#3860 example email address edited in comments
  src/smc-util/message.js
Labels: PR-needs review
