Repository sagemathinc/cocalc, pull requests merged in 2019-08, with the labels that each got.

#3986 Kucalc: API copy status, Take 2
  src/dev/project/start_hub.py
  src/smc-hub/client.coffee
  src/smc-hub/compute-client.coffee
  src/smc-hub/kucalc/compute-client.coffee
  src/smc-hub/test/api/copy-api.sh
  src/smc-util/message.js
Labels: PR-needs review

#3993 hub: handle unhandledRejection events and report them
  src/smc-hub/hub.coffee
Labels: PR-work in progress

#3999 Load directly into target if possible
  src/smc-webapp/history2.ts
  src/smc-webapp/init_app.coffee
  src/smc-webapp/test/history2.test.ts
Labels: PR-needs review

#3995 show more of python formatter errors
  src/smc-project/formatters/python-format.ts
  src/smc-webapp/frame-editors/frame-tree/editor.tsx
Labels: PR-easy, PR-needs review

#4002 webapp/frame editor: fix overlapping buttons
  src/smc-webapp/frame-editors/_style.sass
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
Labels: PR-needs review

#4001 webapp/jupyter: display errors in such a way that pre-formatted text works
  src/smc-webapp/jupyter/main.tsx
  src/smc-webapp/r_misc/error-display.tsx
Labels: PR-easy, PR-needs review

#4005 improve copy paths indexing
  src/smc-util/db-schema.js
Labels: E-easy, PR-needs review

#4003 webapp/frame editor: fix overlapping buttons v2
  src/smc-webapp/frame-editors/_style.sass
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
Labels: PR-needs review

#3998 initialize less when in kiosk mode
  src/smc-webapp/custom-software/init.ts
  src/smc-webapp/entry-point.coffee
  src/smc-webapp/fullscreen.ts
  src/smc-webapp/init_app.coffee
  src/smc-webapp/misc_page2.ts
  src/smc-webapp/projects.cjsx
  src/smc-webapp/prom-client.coffee
  src/smc-webapp/redux_server_stats.coffee
  src/smc-webapp/system_notifications.coffee
  src/smc-webapp/users.cjsx
Labels: E-unclear, PR-needs review

#4012 katex v0.11.0
  src/package.json
  src/smc-webapp/frame-editors/frame-tree/print.ts
  src/smc-webapp/jquery-plugins/katex.ts
  src/smc-webapp/package.json
  src/smc-webapp/share/base-page.tsx
  src/webapp-lib/_inc_head.pug
Labels: PR-easy, PR-needs review

#4014 Jupyter IFrame heuristic
  src/smc-webapp/jupyter/iframe.ts
Labels: PR-needs review

#4016 Add description to mentions email
  src/smc-hub/mentions/handle.ts
Labels: PR-easy, PR-needs review

#4023 typo
  src/webapp-lib/index.pug
Labels: PR-needs review

#4027 a new premium course pricing plan
  src/smc-util/schema.js
  src/smc-util/upgrade-spec.js
  src/webapp-lib/policies/pricing.pug
  src/webpack.config.js
Labels: PR-needs review

#4026 static: reinstate fixed navbar via flex
  src/webapp-lib/_base.pug
  src/webapp-lib/_base.sass
  src/webapp-lib/index.coffee
Labels: PR-needs review

#4024 Type db schema
  src/smc-util/db-schema/account-creation-actions.ts
  src/smc-util/db-schema/accounts.ts
  src/smc-util/db-schema/db-schema.ts
  src/smc-util/db-schema/defaults.ts
  src/smc-util/db-schema/index.ts
  src/smc-util/db-schema/site-defaults.ts
  src/smc-util/db-schema/types.ts
  src/smc-util/message.js
  src/smc-util/schema-static.js
  src/smc-util/schema.js
  src/webpack.config.js
Labels: PR-needs review

#4008 Hub: scheduled copy api
  src/smc-hub/client.coffee
  src/smc-hub/compute-client.coffee
  src/smc-hub/copy-path.ts
  src/smc-hub/kucalc/compute-client.coffee
  src/smc-hub/postgres-base.coffee
  src/smc-hub/test/api/copy-api.sh
  src/smc-hub/test/api/schedule-copy.py
  src/smc-util/message.js
Labels: PR-needs review

#4030 hub/proxy: update http-proxy to 1.17
  src/smc-hub/package.json
Labels: PR-easy, PR-needs review

#4029 hub/api: tweak scheduled copy API doc and fix offset upper limit
  src/smc-hub/copy-path.ts
  src/smc-util/message.js
Labels: PR-easy, PR-needs review

#4042 Upgrade typescript 3.6
  src/package.json
  src/smc-webapp/app-framework.ts
  src/smc-webapp/app-framework/TypedMap.ts
  src/smc-webapp/app-framework/examples/example_stores.ts
  src/smc-webapp/course/main.tsx
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts
  src/smc-webapp/frame-editors/terminal-editor/terminal-manager.ts
  src/smc-webapp/landing-actions.ts
  src/smc-webapp/notifications/mentions/init.ts
  src/smc-webapp/project/file-listing/directory-row.tsx
  src/smc-webapp/project/file-listing/file-row.tsx
  src/smc-webapp/project_store.ts
  src/smc-webapp/projects/project-row.tsx
  src/smc-webapp/stopwatch/register.ts
  src/smc-webapp/tracker/index.ts
  src/smc-webapp/widget-markdown-input/main.tsx
Labels: PR-needs review
