Repository sagemathinc/cocalc, pull requests merged in 2019-10, with the labels that each got.

#4117 Front end test 04
  src/test/puppeteer/README.md
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
  src/test/puppeteer/src/api_create_file.ts
  src/test/puppeteer/src/api_session.ts
  src/test/puppeteer/src/get_account_id.ts
  src/test/puppeteer/src/get_api_key.ts
  src/test/puppeteer/src/get_auth_token.ts
  src/test/puppeteer/src/get_project_id.ts
  src/test/puppeteer/src/install_files.ts
  src/test/puppeteer/src/login_session.ts
  src/test/puppeteer/src/screenshot.ts
  src/test/puppeteer/src/test-creds.ts
  src/test/puppeteer/src/test_driver.ts
  src/test/puppeteer/src/test_sage_ker.ts
  src/test/puppeteer/src/test_tex.ts
  src/test/puppeteer/src/test_widget.ts
  src/test/puppeteer/src/time_log.ts
  src/test/puppeteer/src/types.ts
  src/test/puppeteer/test_files/latex-sample.tex
  src/test/puppeteer/test_files/sage-sample.ipynb
  src/test/puppeteer/test_files/widgets-sample.ipynb
Labels: PR-needs review

#4121 terminal: set MPLBACKEND to tell matplotlib how to draw
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/x11-editor/actions.ts
Labels: PR-needs review

#4119 Ts version of defaults
  src/jest.config.js
  src/smc-util/fill/define.test.ts
  src/smc-util/fill/define.ts
  src/smc-util/fill/fill.test.ts
  src/smc-util/fill/fill.ts
  src/smc-util/fill/index.ts
  src/smc-util/fill/types.ts
  src/smc-util/package-lock.json
  src/smc-util/package.json
  src/smc-webapp/app-framework/Store.ts
Labels: PR-needs review

#4114 Ts project settings.cjsx
  src/package-lock.json
  src/package.json
  src/smc-util/misc2.ts
  src/smc-webapp/app-framework/TypedMap.ts
  src/smc-webapp/collaborators/current-collabs.tsx
  src/smc-webapp/collaborators/new-collabs.tsx
  src/smc-webapp/customize.cjsx
  src/smc-webapp/customize.tsx
  src/smc-webapp/project/explorer/explorer.tsx
  src/smc-webapp/project/jupyterlab-server.tsx
  src/smc-webapp/project/plain-jupyter-server.tsx
  src/smc-webapp/project/project-settings-support.cjsx
  src/smc-webapp/project/settings/body.tsx
  src/smc-webapp/project/settings/hide-delete-box.tsx
  src/smc-webapp/project/settings/index.ts
  src/smc-webapp/project/settings/project-capabilites.tsx
  src/smc-webapp/project/settings/project-control.tsx
  src/smc-webapp/project/settings/quota-console.tsx
  src/smc-webapp/project/settings/sagews-control.tsx
  src/smc-webapp/project/settings/settings.tsx
  src/smc-webapp/project/settings/ssh.tsx
  src/smc-webapp/project/settings/title-description-box.tsx
  src/smc-webapp/project/settings/types.ts
  src/smc-webapp/project/settings/upgrade-usage.tsx
  src/smc-webapp/project/settings/url-box.tsx
  src/smc-webapp/project_new.cjsx
  src/smc-webapp/project_page.cjsx
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/r_misc/index.tsx
  src/smc-webapp/r_misc/labeled-row.tsx
  src/smc-webapp/r_misc/setting-box.tsx
  src/smc-webapp/todo-types.ts
  src/smc-webapp/upgrades/upgrade-utils.ts
Labels: PR-needs review

#4129 Update typescript and @types
  src/smc-project/package-lock.json
  src/smc-project/package.json
Labels: PR-needs review

#4130 Update project ts
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
Labels: PR-needs review

#4135 Popconfirm project restart
  src/cocalc-ui/index.ts
  src/smc-webapp/project/settings/project-control.tsx
Labels: PR-needs review

#4132 sagews: fix compatibility issue with 8.9
  src/smc_sagews/smc_sagews/sage_salvus.py
Labels: PR-careful, PR-needs review

#4138 Npm updates oct 19
  src/package-lock.json
  src/package.json
  src/smc-hub/coffee-coverage-loader.js
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-util-node/coffee-coverage-loader.js
  src/smc-util-node/package-lock.json
  src/smc-util-node/package.json
  src/smc-util/coffee-coverage-loader.js
  src/smc-util/package-lock.json
  src/smc-util/package.json
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#4142 webapp/jupyter2: resize too large images to container width
  src/smc-webapp/jupyter/output-messages/data.tsx
  src/smc-webapp/jupyter/output-messages/image.tsx
Labels: PR-needs review

#4149 webapp/latex: do not set an output if there is none --
  src/smc-webapp/frame-editors/latex-editor/actions.ts
Labels: PR-needs review

#4152 webapp/frame-editor: wrap touch_project call, fails in case of being disconnected
  src/smc-webapp/frame-editors/generic/client.ts
Labels: PR-needs review

#4151 alter wording per issue 4143
  src/smc-webapp/course/configuration_panel.tsx
Labels: PR-needs review

#4154 add index entry for get_api_key
  src/smc-util/message.js
Labels: PR-needs review

#4157 hub/stats: also stats about x11 files
  src/smc-hub/postgres-server-queries.coffee
Labels: PR-needs review

#4161 sagews: update julia to 1.2
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-easy, PR-positive review

#4162 support sage-8.9 in sagews
  src/smc_sagews/smc_sagews/tests/test_sagews.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-needs review

#4163 npm install: delete old node_modules by moving them out of the way
  src/scripts/cocalc-dirs.sh
  src/scripts/smc-install-all
Labels: PR-easy, PR-needs review

#4160 typescript 3.6.4
  src/package-lock.json
  src/package.json
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
Labels: PR-easy, PR-needs review

#4139 preflight: ban specific chrome 77
  src/smc-webapp/init_app.coffee
  src/smc-webapp/jupyter/jupyter-classic-support.ts
  src/smc-webapp/landing_page.cjsx
  src/webapp-lib/preflight-checks.ts
Labels: PR-needs review, blocked

#4178 Front end test 06
  src/smc-webapp/project/settings/hide-delete-box.tsx
  src/smc-webapp/projects/projects-filter-buttons.tsx
  src/test/puppeteer/src/api_create_project.ts
  src/test/puppeteer/src/del_hide_project.ts
  src/test/puppeteer/src/get_project_status.ts
  src/test/puppeteer/src/login_session.ts
  src/test/puppeteer/src/test_driver.ts
  src/test/puppeteer/src/test_sage_ker.ts
  src/test/puppeteer/src/types.ts
Labels: PR-needs review

#4184 webapp/proj navbar: fix low "hanging" tab descriptions
  src/smc-webapp/_projects.sass
Labels: PR-easy, PR-needs review

#4183 minor pricing page changes
  src/smc-webapp/billing/billing-page.tsx
  src/smc-webapp/billing/explain-resources.tsx
  src/smc-webapp/billing/faq.tsx
  src/smc-webapp/r_misc/A.tsx
Labels: PR-easy, PR-needs review

#4175 Update react image crop
  src/smc-webapp/other-users.cjsx
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
  src/smc-webapp/r_misc/index.tsx
  src/smc-webapp/r_misc/profile-icon.tsx
  src/smc-webapp/r_profile_image.tsx
Labels: PR-needs review

#4186 html reload button
  src/smc-webapp/frame-editors/html-editor/actions.ts
  src/smc-webapp/frame-editors/html-editor/iframe-html.tsx
  src/smc-webapp/frame-editors/html-editor/options.ts
Labels: PR-needs review

#4167 webapp: updating dropzone because of #4165
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#4189 verilog file support
  src/smc-webapp/file-associations.ts
Labels: PR-easy, PR-needs review

#4191 dev: consistency checker for npm packages
  .gitignore
  src/package.json
  src/scripts/check_npm_packages.py
Labels: PR-easy, PR-needs review

#4179 Improve typing for Store.getIn and TypedMap.getIn
  src/smc-webapp/app-framework.ts
  src/smc-webapp/app-framework/Store.ts
  src/smc-webapp/app-framework/TypedMap.ts
  src/smc-webapp/app-framework/__tests__/getIn.test.ts
  src/smc-webapp/app-framework/__tests__/store-get-in.type.test.ts
  src/smc-webapp/app-framework/immutable-types.ts
  src/smc-webapp/billing/billing-page.tsx
  src/smc-webapp/billing/invoice-history.tsx
  src/smc-webapp/billing/invoice.tsx
  src/smc-webapp/billing/types.ts
  src/smc-webapp/course/actions.ts
  src/smc-webapp/course/assignments_panel.tsx
  src/smc-webapp/course/handouts_panel.tsx
  src/smc-webapp/course/store.ts
  src/smc-webapp/notifications/mentions/mention-row.tsx
  src/smc-webapp/notifications/notification-list.tsx
  src/smc-webapp/project/settings/hide-delete-box.tsx
  src/smc-webapp/project/settings/project-control.tsx
  src/smc-webapp/project/settings/quota-console.tsx
  src/smc-webapp/project/settings/types.ts
Labels: PR-needs review

#4197 dropzone: reverting #4167 because it stalls when uploading larger files…
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#3985 webapp/kiosk: remotely control an embedded cocalc instance
  src/smc-hub/hub.coffee
  src/smc-hub/server-settings.coffee
  src/smc-hub/server-settings.ts
  src/smc-util/db-schema/site-defaults.ts
  src/smc-webapp/app_shared.cjsx
  src/smc-webapp/app_shared2.tsx
  src/smc-webapp/customize.tsx
  src/smc-webapp/desktop_app.cjsx
  src/smc-webapp/entry-point.coffee
  src/smc-webapp/iframe-communication.ts
  src/smc-webapp/init_app.coffee
  src/smc-webapp/mobile_app.cjsx
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_page.cjsx
  src/smc-webapp/projects.cjsx
  src/smc-webapp/session.ts
  src/smc-webapp/test/iframe-comm.test.ts
  src/smc-webapp/users.cjsx
  src/smc-webapp/widget-ssh-keys/main.cjsx
  src/webapp-lib/app-startup-style.css
Labels: PR-needs review
