Repository sagemathinc/cocalc, pull requests merged in 2019-11, with the labels that each got.

#4204 webapp/rmd: make sure mpl backend is set correctly when plotting via matplotlib
  src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts
Labels: PR-easy, PR-needs review

#4206 webapp/latex/pythontex: tell matplotlib what to use
  src/smc-webapp/frame-editors/latex-editor/pythontex.ts
Labels: PR-easy, PR-needs review

#4211 Front end test 07
  src/test/puppeteer/.eslintrc.js
  src/test/puppeteer/.prettierrc.js
  src/test/puppeteer/README.md
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
  src/test/puppeteer/src/api_create_file.ts
  src/test/puppeteer/src/api_project_exec.ts
  src/test/puppeteer/src/api_session.ts
  src/test/puppeteer/src/del_hide_project.ts
  src/test/puppeteer/src/login_session.ts
  src/test/puppeteer/src/sign_up.ts
  src/test/puppeteer/src/test_driver.ts
  src/test/puppeteer/src/test_sage_ker.ts
  src/test/puppeteer/src/test_sagews.ts
  src/test/puppeteer/src/test_tex.ts
  src/test/puppeteer/src/test_widget.ts
  src/test/puppeteer/src/types.ts
Labels: PR-needs review

#4216 Front end test 08
  src/smc-webapp/app_shared.cjsx
  src/smc-webapp/jupyter/cell-input.tsx
  src/smc-webapp/jupyter/cell-output.tsx
  src/smc-webapp/share/public-path-info.tsx
  src/test/puppeteer/src/api_create_project.ts
  src/test/puppeteer/src/api_project_exec.ts
  src/test/puppeteer/src/api_session.ts
  src/test/puppeteer/src/get_account_id.ts
  src/test/puppeteer/src/get_api_key.ts
  src/test/puppeteer/src/get_auth_token.ts
  src/test/puppeteer/src/get_project_id.ts
  src/test/puppeteer/src/get_project_status.ts
  src/test/puppeteer/src/gui_is_admin.ts
  src/test/puppeteer/src/install_files.ts
  src/test/puppeteer/src/login_session.ts
  src/test/puppeteer/src/test_ir.ts
  src/test/puppeteer/src/test_shared_file.ts
  src/test/puppeteer/src/types.ts
  src/test/puppeteer/test_files/ir-sample.ipynb
Labels: A-testing, PR-needs review

#4219 removing wiki portal link and misc other usages of "wiki"
  src/smc-hub/email.ts
  src/smc-util/theme.js
  src/smc-webapp/buttonbar.coffee
  src/smc-webapp/course/upgrades.tsx
  src/smc-webapp/customize.tsx
  src/smc-webapp/r_help.cjsx
  src/smc-webapp/share/config/config.tsx
  src/smc-webapp/support.cjsx
  src/smc-webapp/tasks/actions.coffee
Labels: PR-needs review

#4235 Front end test 09
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
  src/test/puppeteer/.gitignore
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
  src/test/puppeteer/src/gui_is_admin.ts
  src/test/puppeteer/src/login_session.ts
  src/test/puppeteer/src/sign_up.ts
  src/test/puppeteer/src/test_ir.ts
  src/test/puppeteer/src/test_sage_ker.ts
  src/test/puppeteer/src/test_sagews.ts
  src/test/puppeteer/src/test_shared_file.ts
  src/test/puppeteer/src/test_tex.ts
  src/test/puppeteer/src/test_widget.ts
  src/test/puppeteer/src/types.ts
Labels: PR-needs review

#4221 Upgrade typescript
  src/package-lock.json
  src/package.json
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/smc-webapp/app-framework/Store.ts
  src/smc-webapp/app-framework/TypedMap.ts
  src/smc-webapp/app-framework/__tests__/StoreInheretance.ts
  src/smc-webapp/frame-editors/frame-tree/frame-tree.tsx
  src/smc-webapp/frame-editors/html-editor/iframe-html.tsx
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/notifications/notification-list.tsx
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#4233 npm package updates
  src/package-lock.json
  src/package.json
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/smc-util-node/package-lock.json
  src/smc-util-node/package.json
  src/smc-util/package-lock.json
  src/smc-util/package.json
  src/smc-webapp/jupyter/package-lock.json
  src/smc-webapp/jupyter/package.json
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#4134 hub/stats: get rid of ttl offset, since we are not using cronjob
  src/smc-hub/postgres-server-queries.coffee
Labels: PR-needs work

#4236 formatting support for rust
  src/smc-project/formatters/prettier.ts
  src/smc-project/formatters/rust-format.ts
  src/smc-util/code-formatter.ts
  src/smc-util/misc2.ts
  src/smc-webapp/frame-editors/code-editor/editor.ts
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
Labels: PR-needs review

#4242 simplify default latex template and mention pythontex
  src/smc_pyutil/smc_pyutil/templates/linux/default.tex
Labels: PR-needs review

#4239 webapp/jupyter: change cell type selector to be an antd dropdown
  src/smc-webapp/jupyter/top-buttonbar.tsx
Labels: PR-needs review

#4246 tweaking latex landing page a little bit
  src/webapp-lib/doc/latex-editor.pug
Labels: PR-needs review

#4241 Ts project log.cjsx
  src/smc-webapp/app-framework/TypedMap.ts
  src/smc-webapp/app-framework/__tests__/StoreInheretance.ts
  src/smc-webapp/app-framework/immutable-types.ts
  src/smc-webapp/file-associations.ts
  src/smc-webapp/hooks.ts
  src/smc-webapp/project/history/index.ts
  src/smc-webapp/project/history/log-entry.tsx
  src/smc-webapp/project/history/log.tsx
  src/smc-webapp/project/history/search.tsx
  src/smc-webapp/project/history/system-process.tsx
  src/smc-webapp/project/history/types.ts
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_log.cjsx
  src/smc-webapp/project_page.cjsx
  src/smc-webapp/project_store.ts
  src/smc-webapp/projects.cjsx
Labels: PR-needs review
