Repository sagemathinc/cocalc, pull requests merged in 2019-07, with the labels that each got.

#3933 add "cocalc-test" attribute for front-end testing with puppeteer
  src/smc-webapp/desktop_app.cjsx
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
  src/smc-webapp/frame-editors/latex-editor/latex-word-count.tsx
  src/smc-webapp/jupyter/cell.tsx
  src/smc-webapp/landing-page/sign-in.tsx
  src/smc-webapp/project/file-listing/file-row.tsx
  src/smc-webapp/project/file-tab.cjsx
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/projects/create-project.tsx
  src/smc-webapp/projects/project-row.tsx
  src/smc-webapp/r_misc/index.cjsx
  src/test/puppeteer/README.md
  src/test/puppeteer/api_key.js
  src/test/puppeteer/index.js
  src/test/puppeteer/widget.js
Labels: PR-easy, PR-needs review

#3932 Fchapoton py3
  src/smc_pyutil/smc_pyutil/git_ls.py
  src/smc_pyutil/smc_pyutil/html2sagews.py
  src/smc_pyutil/smc_pyutil/ipynb2sagews.py
  src/smc_pyutil/smc_pyutil/java2html.py
  src/smc_pyutil/smc_pyutil/jupyter_lab.py
  src/smc_pyutil/smc_pyutil/jupyter_notebook.py
  src/smc_pyutil/smc_pyutil/markdown2Mathjax.py
  src/smc_pyutil/smc_pyutil/new_file.py
  src/smc_pyutil/smc_pyutil/restart_smc.py
  src/smc_pyutil/smc_pyutil/smc_close.py
  src/smc_pyutil/smc_pyutil/smc_compute.py
  src/smc_pyutil/smc_pyutil/smc_git.py
  src/smc_pyutil/smc_pyutil/smc_open.py
  src/smc_pyutil/smc_pyutil/smc_top.py
  src/smc_pyutil/smc_pyutil/start_smc.py
  src/smc_pyutil/smc_pyutil/status.py
  src/smc_pyutil/smc_pyutil/stop_smc.py
  src/smc_pyutil/smc_pyutil/update_snapshots.py
  src/smc_sagews/smc_sagews/daemon.py
  src/smc_sagews/smc_sagews/graphics.py
  src/smc_sagews/smc_sagews/julia.py
  src/smc_sagews/smc_sagews/markdown2Mathjax.py
  src/smc_sagews/smc_sagews/sage_parsing.py
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/sage_server.py
  src/smc_sagews/smc_sagews/sage_server_command_line.py
  src/smc_sagews/smc_sagews/tests/a.py
  src/smc_sagews/smc_sagews/tests/conftest.py
  src/smc_sagews/smc_sagews/tests/test_doctests.py
  src/smc_sagews/smc_sagews/tests/test_env.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-careful, PR-work in progress

#3934 analytics scripts: async+defer them and cache noop script
  src/smc-hub/analytics.ts
  src/smc-webapp/share/page.tsx
  src/webapp-lib/_inc_analytics.pug
Labels: PR-easy, PR-needs review

#3936 files listing: split flex divs to avoid #3904
  src/smc-webapp/project_files.cjsx
Labels: PR-careful, PR-needs review

#3937 sagews pytest 2019 07
  src/smc_sagews/smc_sagews/tests/conftest.py
  src/smc_sagews/smc_sagews/tests/test_graphics.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
Labels: PR-needs review

#3944 api uses POST
  src/smc-util/message.js
Labels: A-API, A-documentation, PR-needs review

#3946 URL for cc-in-cc from project
  src/dev/project/README.md
Labels: A-documentation, PR-needs review

#3948 Landing page latex collaborators
  src/webapp-lib/doc/latex-editor.pug
Labels: PR-easy, PR-needs review

#3947 Fix files listing panel
  src/smc-webapp/project/file-listing/file-listing.tsx
  src/smc-webapp/project_files.cjsx
Labels: PR-needs review

#3945 static/pricing: adding section about dedicated VMs
  src/smc-util/upgrade-spec.js
  src/smc-webapp/billing.cjsx
  src/webapp-lib/policies/pricing.pug
Labels: PR-needs review

#3954 webapp: log project uploads
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_log.cjsx
  src/smc-webapp/smc-dropzone.cjsx
Labels: PR-easy, PR-needs review

#3956 announce options for custom plans
  src/smc-webapp/billing.cjsx
Labels: PR-needs review

#3958 invite customization from subscriptions page
  src/smc-webapp/billing.cjsx
Labels: PR-needs review

#3959 prepend WCAG accessibility statement
  src/webapp-lib/policies/_wcag_statement.html
  src/webapp-lib/policies/accessibility.md
  src/webapp-lib/policies/accessibility.pug
Labels: PR-needs review

#3960 static/landing: lazy loading all those images
  src/webapp-lib/_base.pug
  src/webapp-lib/_inc_head.pug
  src/webapp-lib/doc/_terminal.pug
  src/webapp-lib/doc/jupyter-notebook.pug
  src/webapp-lib/doc/latex-editor.pug
  src/webapp-lib/doc/linux.pug
  src/webapp-lib/doc/python.pug
  src/webapp-lib/doc/r-statistical-software.pug
  src/webapp-lib/doc/teaching.pug
  src/webapp-lib/index.coffee
  src/webapp-lib/index.pug
Labels: PR-easy, PR-needs review

#3965 restore invitation to free trial
  src/smc-webapp/billing.cjsx
Labels: PR-needs review

#3967 "contact us" email link
  src/smc-webapp/billing.cjsx
Labels: PR-needs review

#3966 sagews a5 a2019
  src/smc_sagews/smc_sagews/sage_jupyter.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-needs review

#3964 Draft for startup actions
  src/smc-webapp/entry-point.coffee
  src/smc-webapp/landing-actions.ts
  src/smc-webapp/landing-page/sign-in-hooks.ts
  src/smc-webapp/landing_page.cjsx
  src/smc-webapp/misc_page.coffee
  src/smc-webapp/misc_page2.ts
Labels: PR-needs review

#3970 move link from wiki to doc
  src/smc-webapp/course/common.tsx
Labels: PR-needs review

#3977 jupyter: make codemirror indentUnit and tabSize more robust
  src/smc-webapp/jupyter/cm_options.ts
Labels: PR-easy, PR-needs review

#3968 SendGrid invite group ID uses variable instead of hardcode
  src/smc-hub/client.coffee
Labels: PR-needs review

#3980 api: query status of copy path operation
  src/smc-hub/client.coffee
  src/smc-util/message.js
Labels: PR-needs review

#3972 hub/stripe: propagate email changes from our DB to stripe
  src/smc-hub/postgres-server-queries.coffee
  src/smc-hub/stripe/client.ts
  src/smc-hub/stripe/sync.coffee
  src/smc-webapp/billing.cjsx
Labels: PR-careful, PR-needs review

#3982 db: add a "scheduled" field to copy_path for future tasks
  src/smc-util/db-schema.js
Labels: PR-needs review
