Repository sagemathinc/cocalc, pull requests merged in 2019-12, with the labels that each got.

#4263 Fix 3 TS errors
  src/smc-webapp/course/assignments/actions.ts
  src/smc-webapp/course/store.ts
Labels: PR-needs review

#4234 Improve UncommitedChanges Component
  src/smc-webapp/frame-editors/frame-tree/save-button.tsx
  src/smc-webapp/jupyter/uncommitted-changes.tsx
  src/smc-webapp/r_misc/__tests__/__snapshots__/uncommited-changes.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/uncommited-changes.test.tsx
  src/smc-webapp/r_misc/index.tsx
  src/smc-webapp/r_misc/uncommited-changes.tsx
  src/smc-webapp/tasks/buttonbar.cjsx
Labels: PR-needs review

#4269 Fix missing test case
  src/smc-webapp/r_misc/__tests__/__snapshots__/uncommited-changes.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/uncommited-changes.test.tsx
  src/smc-webapp/r_misc/uncommited-changes.tsx
Labels: PR-needs review

#4270 remove "mandatory" sentence & revise wording on pricing page
  src/smc-webapp/billing/explain-plan.tsx
Labels: PR-needs review

#4285 Fix hooks in share server
  src/smc-hub/share/react-viewer.ts
  src/smc-hub/share/render-user.ts
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
  src/smc-webapp/project/new/file-type-selector.tsx
  src/smc-webapp/share/server-render.ts
Labels: PR-needs review

#4289 remove duplicated DedicatedVM entry
  src/smc-webapp/r_upgrades.cjsx
Labels: PR-easy, PR-needs review

#4288 webapp/x11: add grass launch button
  src/smc-webapp/frame-editors/x11-editor/apps.ts
Labels: PR-easy, PR-needs review

#4291 webapp: remove google+
  src/smc-webapp/r_help.cjsx
Labels: E-easy, PR-needs review

#4292 do not hardcode DB credentials
  src/smc-hub/postgres-base.coffee
  src/smc-hub/postgres-ops.coffee
  src/smc-hub/test/get_stats.coffee
Labels: PR-needs review

#4301 add Promise to return types for 2 functions in src/smc-webapp/launch/share.ts
  src/smc-webapp/launch/share.ts
Labels: PR-needs review
