Repository sagemathinc/cocalc, pull requests merged in 2019-02, with the labels that each got.

#3528 webapp: remove local storage warning and add exists function
  src/smc-webapp/misc/__test__/local-storage.test.tsx
  src/smc-webapp/misc/local-storage.ts
Labels: PR-easy, PR-needs review

#3532 webapp/tasks: moving help page
  src/smc-webapp/tasks/actions.coffee
Labels: PR-easy, PR-needs review

#3533 static/r: link movd to doc
  src/webapp-lib/doc/r-statistical-software.pug
Labels: PR-easy, PR-needs review

#3540 weabpp/frame editor: codemirror Ctrl-P does not pass down frame ID
  src/smc-webapp/frame-editors/codemirror/cm-options.ts
Labels: PR-easy, PR-needs review

#3541 webapp/course: search student via shift return
  src/smc-webapp/course/students_panel.tsx
Labels: PR-easy, PR-needs review

#3544 Message coffee comments
  src/smc-hub/test/api/messages.coffee
  src/smc-util/message.js
Labels: PR-needs review

#3550 x11: log launch button
  src/smc-webapp/frame-editors/x11-editor/actions.ts
  src/smc-webapp/project_log.cjsx
Labels: PR-easy, PR-needs review

#3553 More analytics tracking
  src/smc-webapp/account.coffee
  src/smc-webapp/app_shared.cjsx
  src/smc-webapp/collaborators/new-collabs.tsx
  src/smc-webapp/editor.coffee
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/project_miniterm.tsx
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/projects.cjsx
  src/smc-webapp/projects/projects-filter-buttons.tsx
  src/smc-webapp/side_chat.cjsx
  src/smc-webapp/video-chat.cjsx
Labels: PR-easy, PR-needs review

#3555 project/jupyter: set environment only for sage kernels
  src/smc-project/jupyter/jupyter.ts
Labels: PR-easy, PR-needs review

#3558 sagews: %julia 1.1
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-easy, PR-needs review

#3565 webapp/sagews: fix misc.get_extension is not a function
  src/smc-webapp/editor.coffee
Labels: P-high, PR-easy, PR-needs review

#3567 webapp/side_chat: analytics_event was undefined
  src/smc-webapp/side_chat.cjsx
Labels: PR-easy, PR-needs review

#3571 doc: Troubleshooting page moved
  src/smc-hub/email.coffee
Labels: PR-easy, PR-needs review

#3581 jupyter: remove a not-null assertion and update jquery
  src/smc-webapp/jupyter/cell-list.tsx
  src/smc-webapp/package.json
Labels: PR-easy, PR-needs review

#3592 hub startup: fix yet another error TS2581: Cannot find name "$".
  src/smc-webapp/jupyter/cell-input.tsx
Labels: PR-easy, PR-needs review

#3600 webapp: fix title notification count in (..)
  src/smc-webapp/browser.coffee
  src/smc-webapp/file-use/init.ts
Labels: PR-easy, PR-needs review, needs-help

#3597 webapp: register more unknown filetypes, add x11/impress, and tweak icon
  src/smc-webapp/editor-data/generic.tsx
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-easy, PR-needs review

#3616 webapp build: cleanup all of "our" package-lock files
  src/install.py
  src/package.json
  src/scripts/smc-install-all
Labels: PR-easy, PR-needs review

#3615 webapp/latex: update pdfjs 2.0.943
  src/smc-webapp/frame-editors/latex-editor/pdfjs-annotation.tsx
  src/smc-webapp/frame-editors/latex-editor/pdfjs-nonloaded-page.tsx
  src/smc-webapp/frame-editors/latex-editor/pdfjs-page.tsx
  src/smc-webapp/frame-editors/latex-editor/pdfjs.tsx
  src/smc-webapp/package.json
Labels: PR-needs review

#3614 webapp/latex: showing errors of sagetex
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
  src/smc-webapp/frame-editors/latex-editor/sagetex.ts
Labels: PR-needs review

#3623 package.json: just formatting, npm modifies it
  src/package.json
Labels: PR-easy, PR-needs review

#3624 proj/x11 server: type spawn options
  src/smc-project/x11/server.ts
Labels: PR-needs review

#3627 help button links moved to user manual
  src/smc-webapp/support.cjsx
Labels: A-help, PR-needs review

#3432 Project uptime fix
  src/smc-webapp/project_settings.cjsx
Labels: PR-kucalc, PR-needs review

#3631 make projects nodejs 8 and 10 compatible
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/smc-util-node/memory.coffee
  src/smc-util-node/package-lock.json
  src/smc-util-node/package.json
Labels: PR-needs review
