Repository sagemathinc/cocalc, pull requests merged in 2019-03, with the labels that each got.

#3636 static: do not report query params to GA
  src/webapp-lib/_inc_analytics.pug
Labels: PR-needs review

#3638 webapp/miniterm: restrict max width to avoid being off screen
  src/smc-webapp/project_miniterm.tsx
Labels: PR-easy, PR-needs review

#3640 webapp/projects: memory/oom page moved
  src/smc-webapp/project_warnings.cjsx
Labels: PR-easy, PR-needs review

#3313 katex 0.10.1 and fixing CSS files via CDN
  src/package.json
  src/smc-webapp/frame-editors/frame-tree/print.ts
  src/smc-webapp/package.json
  src/smc-webapp/share/page.cjsx
  src/webapp-lib/_inc_head.pug
Labels: PR-needs review

#3649 webapp/video chat: there could be no video window
  src/smc-webapp/video-chat.cjsx
Labels: PR-easy, PR-needs review

#3654 doc: little extractor to get a serialized representation of the api doc
  .gitignore
  src/scripts/export-api-doc.ts
Labels: PR-needs review

#3661 Fix width styling and send button
  src/smc-webapp/smc_chat.tsx
Labels: PR-needs review

#3655 api: fixing docstrings for usage in doc.cocalc.com
  src/smc-util/message.js
Labels: PR-needs review

#3645 project: clean env for spawning
  src/smc-project/local_hub.coffee
Labels: PR-needs review

#3641 Ts r misc
  docs/upgrading-packages.md
  src/jest.config.js
  src/package.json
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/r_misc/__tests__/__snapshots__/error-display.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/__snapshots__/number-input.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/__snapshots__/simple-x.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/__snapshots__/skinny-error.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/__snapshots__/spinner.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/__snapshots__/text-input.test.tsx.snap
  src/smc-webapp/r_misc/__tests__/error-display.test.tsx
  src/smc-webapp/r_misc/__tests__/number-input.test.tsx
  src/smc-webapp/r_misc/__tests__/simple-x.test.tsx
  src/smc-webapp/r_misc/__tests__/skinny-error.test.tsx
  src/smc-webapp/r_misc/__tests__/spinner.test.tsx
  src/smc-webapp/r_misc/__tests__/text-input.test.tsx
  src/smc-webapp/r_misc/error-display.tsx
  src/smc-webapp/r_misc/index.cjsx
  src/smc-webapp/r_misc/labeled-row.tsx
  src/smc-webapp/r_misc/number-input.tsx
  src/smc-webapp/r_misc/simple-x.tsx
  src/smc-webapp/r_misc/skinny-error.tsx
  src/smc-webapp/r_misc/spinner.tsx
  src/smc-webapp/r_misc/text-input.tsx
Labels: PR-needs work

#3672 pyutil: fix link to sagetex help
  src/smc_pyutil/smc_pyutil/templates/linux/default.tex
Labels: PR-easy, PR-needs review

#3673 Fix pasting in an image and refocus
  src/smc-webapp/side_chat.cjsx
  src/smc-webapp/smc_chat.tsx
Labels: PR-needs review

#3677 Latex shell escape
  src/smc-webapp/frame-editors/latex-editor/build-command.tsx
  src/smc-webapp/frame-editors/latex-editor/clean.ts
  src/smc-webapp/frame-editors/latex-editor/latexmk.ts
  src/smc-webapp/project_store.ts
Labels: PR-easy, PR-needs review

#3682 webapp+share: fix rendering of jupyter notebooks
  src/smc-webapp/jupyter/codemirror.tsx
Labels: E-unclear

#3681 static: link to documentation pages from enhanced features page and the top level navbar
  src/smc-util/theme.js
  src/webapp-lib/_base.pug
  src/webapp-lib/doc/api.coffee
  src/webapp-lib/doc/api.pug
  src/webapp-lib/doc/features.pug
Labels: PR-easy, PR-needs review

#3684 Fix #3678 and memoize user data computation
  src/smc-webapp/chat/actions.coffee
  src/smc-webapp/chat/input.tsx
  src/smc-webapp/chat/store.ts
  src/smc-webapp/editor_chat.cjsx
  src/smc-webapp/package.json
  src/smc-webapp/side_chat.cjsx
  src/smc-webapp/smc-dropzone.cjsx
  src/smc-webapp/smc_chat.tsx
Labels: PR-work in progress

#3687 Fix message length problems in chat rooms
  src/smc-webapp/smc_chat.tsx
Labels: PR-needs review

#3700 New trial project page
  src/smc-webapp/project_page.cjsx
Labels: PR-needs review

#3705 Performance
  src/smc-webapp/package.json
  src/smc-webapp/project/file-listing/directory-row.tsx
  src/smc-webapp/project/file-listing/file-checkbox.tsx
  src/smc-webapp/project/file-listing/file-listing.tsx
  src/smc-webapp/project/file-listing/file-row.tsx
  src/smc-webapp/project/file-listing/no-files.tsx
  src/smc-webapp/project_actions.ts
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/project_store.ts
  src/smc-webapp/projects/project-row.tsx
  src/smc-webapp/react-virtualized-mock.tsx
Labels: PR-needs review

#3713 ask explicitly about filename, after selecting the type
  src/smc-webapp/project/ask-filename.tsx
  src/smc-webapp/project_files.cjsx
  src/smc-webapp/r_misc/index.cjsx
Labels: PR-needs review
