Repository sagemathinc/cocalc, pull requests merged in 2019-06, with the labels that each got.

#3861 webapp: rename assistant to snippets
  src/scripts/postgresql/cool-queries.md
  src/smc-webapp/assistant/body.cjsx
  src/smc-webapp/assistant/dialog.cjsx
  src/smc-webapp/assistant/footer.cjsx
  src/smc-webapp/assistant/header.cjsx
  src/smc-webapp/assistant/legacy.cjsx
  src/smc-webapp/assistant/main.coffee
  src/smc-webapp/editor.coffee
  src/smc-webapp/editor.html
  src/smc-webapp/frame-editors/sagews-editor/editor.ts
  src/smc-webapp/jupyter/browser-actions.ts
  src/smc-webapp/jupyter/commands.ts
  src/smc-webapp/jupyter/main.tsx
  src/smc-webapp/jupyter/register.ts
  src/smc-webapp/jupyter/store.ts
  src/smc-webapp/jupyter/top-buttonbar.tsx
Labels: PR-needs review

#3866 webapp/file listing: for admins, always assume project is running
  src/smc-webapp/project_files.cjsx
Labels: PR-needs review

#3871 landing: terminal content
  src/webapp-lib/doc/linux-terminal.pug
Labels: PR-easy, PR-needs review

#3874 webapp/new files: if no project config is available, fallback to offer all file extensions
  src/smc-webapp/project_files.cjsx
Labels: PR-easy, PR-needs review

#3876 webapp/jupyter: misc tweaks to the links in the help menu
  src/smc-webapp/jupyter/help-links.js
  src/smc-webapp/jupyter/help-links.ts
  src/smc-webapp/jupyter/top-menubar.tsx
Labels: E-easy, PR-needs review

#3880 front-end tests for CoCalc in puppeteer
  src/test/puppeteer/.gitignore
  src/test/puppeteer/README.md
  src/test/puppeteer/api_key.js
  src/test/puppeteer/index.js
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
  src/test/puppeteer/widget.js
  src/test/selenium/tests/conftest.py
  src/test/selenium/tests/test_landing.py
Labels: PR-needs review

#3877 fix manifest file
  src/webapp-lib/_inc_head.pug
  src/webapp-lib/cocalc.manifest
  src/webapp-lib/manifest.json
Labels: PR-easy, PR-needs review

#3881 Doc get api key
  src/smc-util/message.js
Labels: PR-needs review

#3809 enhance cocalc analytics tracking
  src/smc-hub/analytics-script.ts
  src/smc-hub/analytics.ts
  src/smc-hub/auth.coffee
  src/smc-hub/client.coffee
  src/smc-hub/client/create-account.ts
  src/smc-hub/hub_http_server.coffee
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-hub/sign-in.coffee
  src/smc-util/client.coffee
  src/smc-util/db-schema.js
  src/smc-util/message-types.ts
  src/smc-util/message.js
  src/smc-util/misc.js
  src/smc-webapp/landing-page/sign-in-hooks.ts
  src/smc-webapp/misc_page.coffee
  src/smc-webapp/redux_account.coffee
  src/smc-webapp/share/page.tsx
  src/webapp-lib/_inc_analytics.pug
  src/webpack.config.js
Labels: PR-positive review

#3889 webapp/jupyter: ihaskell → haskell substition for codemirror mode
  src/smc-webapp/jupyter/actions.ts
  src/smc-webapp/jupyter/cm_options.ts
Labels: PR-needs review

#3888 multi_response query not supported by api
  src/smc-util/message.js
Labels: PR-needs review

#3886 landing: generalizing linux terminal to online linux environment
  src/webapp-lib/_base.pug
  src/webapp-lib/doc/features.pug
  src/webapp-lib/doc/linux-terminal.pug
  src/webapp-lib/doc/linux.pug
Labels: PR-needs review

#3895 webapp/terminal: desc.get('args') could exist but is still undefined …
  src/smc-webapp/frame-editors/terminal-editor/terminal.tsx
Labels: PR-needs review

#3896 webapp/fix quota calculation
  src/smc-webapp/project_settings.cjsx
  src/smc-webapp/projects.cjsx
Labels: PR-needs review

#3906 webapp/quotas: make sure all quotas exist in the dict of upgrades to avoid NaN vals
  src/smc-webapp/projects.cjsx
Labels: PR-easy, PR-needs review

#3908 webapp/editor: available features could be undefined
  src/smc-webapp/frame-editors/settings/editor.tsx
Labels: PR-easy, PR-needs review

#3911 Sagews2pdf set engine
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/latexmk.ts
  src/smc_pyutil/smc_pyutil/sagews2pdf.py
Labels: PR-work in progress

#3914 Issue/3913
  src/smc-webapp/frame-editors/code-editor/actions.ts
Labels: PR-easy, PR-needs review

#3917 hub/api: attempt to fix #3916 (not tested)
  src/smc-hub/client.coffee
Labels: PR-careful, PR-needs review

#3930 Clear computed size cache on window resize
  src/smc-webapp/project/file-listing/file-listing.tsx
Labels: PR-easy, PR-needs review
