Repository sagemathinc/cocalc, pull requests merged in 2019-04, with the labels that each got.

#3725 webapp: add audio player for ogg, mp3, ...
  src/smc-webapp/editor-data/generic.tsx
  src/smc-webapp/file-associations.ts
  src/smc-webapp/media-viewer/register.coffee
  src/smc-webapp/media-viewer/viewer.cjsx
Labels: PR-easy, PR-needs review

#3724 associate .markdown files with markdown editor -- #3723
  src/smc-webapp/file-associations.ts
  src/smc-webapp/frame-editors/markdown-editor/register.ts
Labels: PR-easy, PR-needs review

#3702 x11: disable mDNS, xpra 2.5
  src/smc-webapp/frame-editors/x11-editor/xpra-server.ts
Labels: PR-needs review

#3728 webapp: do not open jar files
  src/smc-webapp/editor-data/generic.tsx
Labels: PR-easy, PR-needs review

#3727 start of selenium tests for CoCalc
  src/test/selenium/.gitignore
  src/test/selenium/README.md
  src/test/selenium/tests/conftest.py
  src/test/selenium/tests/test_landing.py
Labels: PR-needs review

#3733 kmz files are binary
  src/smc-webapp/editor-data/generic.tsx
Labels: PR-needs review

#3735 sagews pytest: sage-8.7, sagemath doctest
  src/smc_sagews/smc_sagews/tests/README.md
  src/smc_sagews/smc_sagews/tests/runtests.sh
  src/smc_sagews/smc_sagews/tests/test_doctests.py
  src/smc_sagews/smc_sagews/tests/test_sagews.py
  src/smc_sagews/smc_sagews/tests/test_sagews_modes.py
Labels: PR-needs review

#3736 one-letter typo
  src/smc-webapp/r_misc/index.cjsx
Labels: PR-needs review

#3738 Simplyify OOM message
  src/smc-webapp/project_warnings.cjsx
Labels: PR-needs review

#3757 webapp: fallback error message when react crashes
  src/smc-webapp/crash.html
  src/smc-webapp/desktop_app.cjsx
  src/smc-webapp/entry-point.coffee
  src/smc-webapp/html.coffee
  src/smc-webapp/index.sass
  src/smc-webapp/init_app.coffee
  src/smc-webapp/mobile_app.cjsx
Labels: PR-needs review

#3763 webapp/jupyter: fix deletable icon indicator
  src/smc-webapp/jupyter/cell-input.tsx
  src/smc-webapp/jupyter/cell-list.tsx
  src/smc-webapp/jupyter/cell.tsx
Labels: PR-needs review

#3779 Change message for malformed account id
  src/smc-webapp/users.cjsx
Labels: PR-easy, PR-needs review

#3780 webapp/x11: add scilab button
  src/smc-webapp/frame-editors/x11-editor/launcher.tsx
Labels: PR-easy, PR-positive review
