Repository sagemathinc/cocalc, pull requests merged in 2020-03, with the labels that each got.

#4425 Landing page tweaks
  src/smc-webapp/client/anonymous-setup.ts
  src/smc-webapp/client/welcome-file.ts
  src/smc-webapp/project_actions.ts
  src/webapp-lib/_base.pug
  src/webapp-lib/_base.sass
  src/webapp-lib/_inc_head.pug
  src/webapp-lib/about.pug
  src/webapp-lib/doc/_style.sass
  src/webapp-lib/doc/_terminal.pug
  src/webapp-lib/doc/api.pug
  src/webapp-lib/doc/index.pug
  src/webapp-lib/doc/jupyter-notebook.pug
  src/webapp-lib/doc/latex-editor.pug
  src/webapp-lib/doc/linux.pug
  src/webapp-lib/doc/python.pug
  src/webapp-lib/doc/r-statistical-software.pug
  src/webapp-lib/doc/software-executables.pug
  src/webapp-lib/doc/software-julia.pug
  src/webapp-lib/doc/software-python.pug
  src/webapp-lib/doc/software-r.pug
  src/webapp-lib/doc/software.pug
  src/webapp-lib/doc/teaching.pug
  src/webapp-lib/doc/terminal.pug
  src/webapp-lib/doc/x11.pug
  src/webapp-lib/index.pug
  src/webapp-lib/policies/index.pug
  src/webpack.config.js
Labels: PR-needs review

#4430 webapp/copy files: prefix all names with ./
  src/smc-webapp/project_actions.ts
Labels: PR-needs review

#4427 site-settings: moving stripe to all the "extras" and refactor types
  src/smc-util/db-schema/site-defaults.ts
  src/smc-util/db-schema/site-settings-extras.ts
  src/smc-util/db-schema/site-settings.ts
  src/smc-util/db-schema/types.ts
  src/smc-webapp/admin/page.tsx
  src/smc-webapp/admin/site-settings.tsx
  src/smc-webapp/admin/stripe-api-keys.tsx
Labels: PR-needs review

#4435 webapp/admin/site settings: reveal stripe publishable key
  src/smc-util/db-schema/site-settings-extras.ts
Labels: PR-easy, PR-needs review

#4429 hub: landing pages server plugin
  .gitignore
  src/dev/project/start_hub.py
  src/scripts/service_hub.py
  src/smc-hub/hub.coffee
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-util/schema-static.ts
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#4446 site-settings: add GA token for cocalc.com only
  src/smc-util/db-schema/site-defaults.ts
Labels: PR-needs review

#4447 further work on site licenses
  src/smc-hub/postgres-server-queries.coffee
  src/smc-hub/postgres/site-license/analytics.ts
  src/smc-util/db-schema/site-licenses.ts
  src/smc-webapp/admin/users/projects.tsx
  src/smc-webapp/site-licenses/admin/license.tsx
Labels: PR-work in progress

#4453 webapp: fixing firefox display of uncommitted saving warning
  src/smc-webapp/r_misc/uncommited-changes.tsx
Labels: PR-needs review

#4454 Fix pythontex errorpath
  src/smc-webapp/frame-editors/latex-editor/actions.ts
  src/smc-webapp/frame-editors/latex-editor/errors-and-warnings.tsx
  src/smc-webapp/frame-editors/latex-editor/pythontex.ts
  src/smc-webapp/frame-editors/latex-editor/sagetex.ts
Labels: PR-needs review

#4470 npm: pretter2 + minor upgrades
  src/package-lock.json
  src/package.json
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-project/jupyter/package-lock.json
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/smc-util-node/package-lock.json
  src/smc-util/package-lock.json
  src/smc-webapp/package-lock.json
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
Labels: PR-needs review

#4477 pyutil/cc-ipynb-to-pdf: make it work with spaces in filenames
  src/smc_pyutil/smc_pyutil/ipynb_to_pdf.py
Labels: PR-needs review

#4481 listings: debonuce harder, but also fire a change when it happens
  src/smc-project/sync/listings.ts
  src/smc-project/sync/path-watcher.ts
Labels: A-project listing, PR-easy, PR-needs review
