Repository sagemathinc/cocalc, pull requests merged in 2020-09, with the labels that each got.

#4827 webapp/project: just hide software upgrade banner
  src/smc-webapp/project/page/software-env-upgrade.tsx
Labels: PR-needs review

#4830 project: update better-sqlite3 & dependencies
  src/smc-project/package-lock.json
  src/smc-project/package.json
Labels: PR-needs review

#4831 webapp/software update: reorder some lines to avoid violating hook rules
  src/smc-webapp/project/page/software-env-upgrade.tsx
Labels: PR-needs work

#4834 webapp: loading compute_images in minimal mode
  src/smc-webapp/custom-software/init.ts
Labels: PR-needs review

#4837 pyutil/ipynb2pdf: check for chrome or chromium
  src/smc_pyutil/smc_pyutil/ipynb_to_pdf.py
Labels: PR-easy, PR-needs review

#4840 project capabilities: check if html2pdf via chrome/chromium is available
  src/smc-project/configuration.ts
  src/smc-webapp/project/settings/project-capabilites.tsx
  src/smc-webapp/project_configuration.ts
  src/smc_pyutil/smc_pyutil/ipynb_to_pdf.py
Labels: PR-needs review

#4819 hub/auth: use cookie to transport token to UI
  src/smc-hub/auth.ts
  src/smc-hub/client.coffee
  src/smc-hub/password.coffee
  src/smc-webapp/client/password-reset.ts
Labels: PR-needs review

#4841 pricing: do not show course packages (quick n dirty)
  src/smc-webapp/billing/explain-resources.tsx
  src/smc-webapp/billing/static-pricing-page.tsx
Labels: PR-needs review

#4843 expose country info in client site configuration
  src/smc-hub/hub_http_server.coffee
  src/smc-webapp/customize.tsx
Labels: PR-needs review

#4849 get rid of reacts-widgets + some "globalization" setup
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
  src/smc-webapp/project/explorer/action-box.tsx
  src/smc-webapp/projects/store.ts
  src/smc-webapp/r_misc/old-coffee-code-index.cjsx
  src/webapp-css.js
Labels: PR-careful, PR-needs review

#4812 half-baked whitelabeing idea
  src/smc-hub/hub_http_server.coffee
  src/smc-hub/whitelabel-configuration.ts
  src/smc-util/db-schema/index.ts
  src/smc-util/db-schema/site-defaults.ts
  src/smc-util/db-schema/site-whitelabeling.ts
  src/webapp-css.js
Labels: PR-needs review

#4856 project: remove a use of this.log after closing
  src/smc-project/sync/server.ts
Labels: PR-needs review

#4858 nbgrader: octave templates
  src/smc-webapp/jupyter/nbgrader/cell-types.ts
Labels: PR-needs review

#4855 npm: updating prettier + audit fixes
  src/package-lock.json
  src/package.json
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-project/jupyter/package-lock.json
  src/smc-project/package-lock.json
  src/smc-project/package.json
  src/smc-util-node/package-lock.json
  src/smc-util-node/package.json
  src/smc-util/code-formatter.ts
  src/smc-util/package-lock.json
  src/smc-util/package.json
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
  src/smc-webapp/project_configuration.ts
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
Labels: PR-needs review

#4862 quota function broken
  src/smc-hub/test/kucalc/quota.test.ts
  src/smc-util/upgrades/quota.ts
Labels: PR-needs review

#4864 add site setting to configure restricted countries
  src/smc-util/db-schema/site-defaults.ts
Labels: PR-needs review

#4866 minimal docs for api license calls
  src/smc-util/message.js
Labels: PR-needs review

#4871 Pricing info licenses
  src/smc-webapp/billing/data.ts
  src/smc-webapp/billing/explain-course-licenses.tsx
  src/smc-webapp/billing/explain-plan.tsx
  src/smc-webapp/billing/explain-resources.tsx
  src/smc-webapp/billing/static-pricing-page.tsx
  src/smc-webapp/site-licenses/purchase/purchase.tsx
  src/smc-webapp/site-licenses/purchase/util.ts
Labels: PR-needs review

#4863 npm: fix node-forge, update jest (reverse dependency), etc.
  src/package-lock.json
  src/package.json
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-util/package-lock.json
  src/smc-util/package.json
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
Labels: PR-needs review

#4872 update pricing spec date
  src/smc-util/upgrade-spec.js
Labels: PR-needs review

#4869 project: remove console server
  src/smc-project/bin/smc-console-server
  src/smc-project/browser-websocket/realpath.ts
  src/smc-project/console_server.coffee
  src/smc-project/console_server_child.coffee
  src/smc-project/console_session_manager.coffee
  src/smc-project/index.js
  src/smc-project/local_hub.coffee
Labels: PR-needs review

#4865 combine 4 initial http requests into one and optimize them
  src/smc-hub/auth.ts
  src/smc-hub/hub_http_server.coffee
  src/smc-hub/postgres-server-queries.coffee
  src/smc-hub/utils.ts
  src/smc-hub/webapp-configuration.ts
  src/smc-hub/whitelabel-configuration.ts
  src/smc-webapp/account/init.ts
  src/smc-webapp/account/settings/account-settings.tsx
  src/smc-webapp/account/settings/strategies.ts
  src/smc-webapp/customize.tsx
  src/smc-webapp/landing-page/landing-page.tsx
  src/smc-webapp/landing-page/registration.ts
  src/webapp-lib/app-init.ts
Labels: PR-positive review

#4873 clear terminal
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
  src/smc-webapp/frame-editors/frame-tree/types.ts
  src/smc-webapp/frame-editors/terminal-editor/connected-terminal.ts
  src/smc-webapp/frame-editors/terminal-editor/editor.ts
  src/smc-webapp/frame-editors/terminal-editor/terminal-manager.ts
Labels: PR-needs review

#4876 course: remove license if student is deleted
  src/smc-webapp/course/student-projects/actions.ts
Labels: PR-needs review

#4874 landing/pricing: license subscription examples
  src/smc-webapp/billing/explain-course-licenses.tsx
  src/smc-webapp/billing/explain-plan.tsx
  src/smc-webapp/billing/explain-resources.tsx
  src/smc-webapp/billing/license-examples.tsx
  src/smc-webapp/billing/on-prem.tsx
  src/smc-webapp/billing/static-pricing-page.tsx
  src/smc-webapp/billing/subscription-licenses.tsx
  src/smc-webapp/site-licenses/purchase/purchase.tsx
  src/smc-webapp/site-licenses/purchase/util.ts
Labels: PR-needs review

#4870 optimize project memory usage
  src/smc-project/browser-websocket/api.ts
  src/smc-project/client.coffee
  src/smc-project/formatters/clang-format.ts
  src/smc-project/formatters/gofmt.ts
  src/smc-project/formatters/index.ts
  src/smc-project/formatters/prettier-lib.ts
  src/smc-project/formatters/rust-format.ts
  src/smc-project/init-program.js
  src/smc-project/jupyter/jupyter-blobs-sqlite.ts
  src/smc-project/jupyter/jupyter.ts
  src/smc-project/local_hub.coffee
  src/smc-webapp/frame-editors/code-editor/actions.ts
  src/smc-webapp/frame-editors/generic/client.ts
  src/smc-webapp/jupyter/actions.ts
  src/smc-webapp/project/websocket/api.ts
  src/smc-webapp/project/websocket/types.ts
Labels: PR-needs review

#4885 change of address
  src/smc-util/theme.js
Labels: PR-needs review

#4895 webapp/lean: safeguard debounced calls -- addresses some of #4893
  src/smc-webapp/frame-editors/lean-editor/actions.ts
Labels: needs-help

#4892 project/jupyter: rename _identity to identity
  src/smc-project/jupyter/jupyter.ts
Labels: PR-needs review

#4902 clean button a unicode skull and change Icon to be a FC
  src/smc-webapp/frame-editors/frame-tree/title-bar.tsx
  src/smc-webapp/project/explorer/file-listing/listing-header.tsx
  src/smc-webapp/r_misc/icon.tsx
Labels: PR-needs review
