Repository sagemathinc/cocalc, pull requests merged in 2020-02, with the labels that each got.

#4357 add to project_exec doc
  src/smc-util/message.js
Labels: PR-needs review

#4360 Front end test 10
  src/test/puppeteer/package-lock.json
  src/test/puppeteer/package.json
  src/test/puppeteer/src/api_create_file.ts
  src/test/puppeteer/src/api_create_project.ts
  src/test/puppeteer/src/api_project_exec.ts
  src/test/puppeteer/src/api_session.ts
  src/test/puppeteer/src/create_account.ts
  src/test/puppeteer/src/del_hide_project.ts
  src/test/puppeteer/src/get_account_id.ts
  src/test/puppeteer/src/get_api_key.ts
  src/test/puppeteer/src/get_auth_token.ts
  src/test/puppeteer/src/get_project_id.ts
  src/test/puppeteer/src/get_project_status.ts
  src/test/puppeteer/src/gui_is_admin.ts
  src/test/puppeteer/src/install_files.ts
  src/test/puppeteer/src/login_session.ts
  src/test/puppeteer/src/sign_up.ts
  src/test/puppeteer/src/test_driver.ts
  src/test/puppeteer/src/test_ir.ts
  src/test/puppeteer/src/test_sage_ker.ts
  src/test/puppeteer/src/test_sagews.ts
  src/test/puppeteer/src/test_shared_file.ts
  src/test/puppeteer/src/test_tex.ts
  src/test/puppeteer/src/test_widget.ts
  src/test/puppeteer/src/time_log.ts
  src/test/puppeteer/src/types.ts
Labels: PR-needs review

#4338 make default and max upgrade quotas configurable
  src/smc-hub/kucalc/quota.ts
  src/smc-hub/test/kucalc/quota.coffee
  src/smc-util/db-schema/site-defaults.ts
  src/smc-util/upgrade-spec.js
  src/smc-webapp/admin/site-settings.tsx
  src/smc-webapp/customize.tsx
  src/smc-webapp/project/settings/body.tsx
  src/smc-webapp/project/settings/project-control.tsx
Labels: PR-needs review

#4218 fix cookie for embedding
  src/smc-hub/auth.coffee
  src/smc-hub/client.coffee
  src/smc-hub/hub.coffee
  src/smc-hub/hub_http_server.coffee
  src/smc-hub/package-lock.json
  src/smc-hub/package.json
  src/smc-hub/proxy.coffee
  src/smc-hub/user-api.coffee
  src/smc-hub/user-query.coffee
  src/smc-hub/user-remember-me.coffee
  src/smc-util/client.coffee
  src/smc-util/consts.ts
  src/smc-webapp/package-lock.json
  src/smc-webapp/package.json
  src/smc-webapp/set-version-cookie.js
  src/webapp-smc.coffee
Labels: PR-needs review

#4366 project/config: set PATH var via env option
  src/smc-project/configuration.ts
Labels: PR-easy, PR-needs work

#4370 make the discord link configurable and let it to point to the main room
  src/smc-util/theme.js
  src/smc-webapp/info/links.tsx
  src/smc-webapp/projects.cjsx
  src/smc-webapp/side_chat.cjsx
  src/smc-webapp/smc_chat.tsx
  src/smc-webapp/support.cjsx
Labels: PR-easy, PR-needs review

#4377 webapp/rmd: increase timeout to 4 minutes
  src/smc-webapp/frame-editors/rmd-editor/rmd-converter.ts
Labels: PR-easy, PR-needs review

#4375 filter disabled jupyter kernels
  src/smc-webapp/jupyter/actions.ts
  src/smc-webapp/jupyter/store.ts
Labels: PR-needs review

#4371 quota function cleanup
  src/smc-hub/kucalc/quota.ts
  src/smc-hub/test/kucalc/quota.coffee
Labels: PR-needs review

#4384 move SignOut on top to be always accessible
  src/smc-webapp/account_page.cjsx
  src/smc-webapp/r_account.cjsx
Labels: PR-needs review

#4388 app page: tweak error message and fix some CSS
  src/webapp-lib/app-startup-style.css
  src/webapp-lib/app.pug
Labels: PR-needs review

#4402 Privacy shield 2020 02
  src/webapp-lib/policies/_sagemath_privacy_policy.html
  src/webapp-lib/policies/privacy.pug
Labels: A-documentation, PR-needs review

#4401 webapp/project log: fix impendance between recording and showing downloaded files
  src/smc-webapp/project/explorer/action-box.tsx
  src/smc-webapp/project/history/log-entry.tsx
  src/smc-webapp/project/history/types.ts
  src/smc-webapp/project_actions.ts
Labels: PR-needs review

#4398 share/sagews: sanitize "value" in raw input
  src/smc-webapp/sagews/output.tsx
Labels: PR-needs review

#4400 hub: assume everywhere that createHmac can throw and take some action…
  src/smc-hub/auth.coffee
  src/smc-hub/client.coffee
  src/smc-hub/proxy.coffee
Labels: PR-needs review

#4397 jupyter/traceback: make traceback processing more robust
  src/smc-webapp/jupyter/output-messages/traceback.tsx
Labels: PR-needs review

#4395 inconsistent use of "instead_of_change"
  src/smc-util/db-schema/db-schema.ts
  src/smc-util/db-schema/types.ts
Labels: P-high, PR-needs review

#4396 hub/email: users might sign up but still have no email address
  src/smc-hub/email.ts
Labels: E-easy, PR-needs review

#4368 re-enabled email verification and extend server settings configuration
  src/smc-hub/auth.coffee
  src/smc-hub/email.ts
  src/smc-util/db-schema/db-schema.ts
  src/smc-util/db-schema/site-defaults.ts
  src/smc-util/db-schema/site-settings-extras.ts
  src/smc-webapp/account_page.cjsx
  src/smc-webapp/admin/site-settings.tsx
  src/smc-webapp/customize.tsx
  src/smc-webapp/r_account.cjsx
Labels: dependencies

#4409 webapp/latex/rnw: do not break build upon knitr warnings, only errors!
  src/smc-util/smc-version.js
  src/smc-webapp/frame-editors/latex-editor/actions.ts
Labels: P-high, PR-needs review

#4408 webapp/latex: do not set output-dir for pythontex or sagetex -- #4394
  src/smc-webapp/frame-editors/latex-editor/actions.ts
Labels: PR-needs review

#4406 webapp/rmd: do not mangle dirname of rmd preview file
  src/smc-webapp/frame-editors/rmd-editor/utils.ts
Labels: E-easy, PR-needs review

#4407 hub: add "expire" cols to tables collecting errors
  src/smc-hub/postgres-server-queries.coffee
  src/smc-util/db-schema/central-log.ts
  src/smc-util/db-schema/db-schema.ts
Labels: PR-needs review

#4411 mention backblaze in the list of third parties
  src/webapp-lib/policies/thirdparties.pug
Labels: PR-needs review

#4418 sagews: fix obj? introspection for 9.0 and some code cleanup
  src/smc_sagews/smc_sagews/sage_parsing.py
Labels: PR-needs review
