Repository sagemathinc/cocalc, pull requests merged in 2021-08, with the labels that each got.

#5450 Purchase tab: remove course buttons
  src/packages/frontend/billing/add-subscription.tsx
Labels: PR-needs review

#5446 X11: octave gui and spyder
  src/packages/frontend/frame-editors/x11-editor/apps.ts
Labels: PR-needs review

#5456 frontend: support assembler code
  src/packages/frontend/codemirror/modes.js
  src/packages/frontend/file-associations.ts
Labels: PR-needs review, needs-help

#5460 hub: fix "sign up"
  src/packages/hub/package-lock.json
  src/packages/hub/package.json
  src/packages/hub/postgres-server-queries.coffee
  src/packages/util-node/package-lock.json
  src/packages/util-node/package.json
  src/packages/util-node/server-settings/customize.ts
  src/packages/util-node/server-settings/server-settings.ts
Labels: PR-needs review

#5461 missing return in quota display
  src/packages/frontend/project/info/project-info.tsx
Labels: PR-needs review, PR-easy
