Repository sagemathinc/cocalc, pull requests merged in 2022-05, with the labels that each got.

#5911 frontend/latex: add "no output dir" options and some fixes to sanitization functions
  src/packages/frontend/frame-editors/latex-editor/actions.ts
  src/packages/frontend/frame-editors/latex-editor/build-command.tsx
  src/packages/frontend/frame-editors/latex-editor/latexmk.ts
  src/packages/frontend/frame-editors/latex-editor/util.ts
Labels: PR-needs review

#5916 frontend/x11: change spyder icon to the one for python
  src/packages/frontend/frame-editors/x11-editor/apps.ts
Labels: PR-needs review

#5914 latex: introduce support for !TeX cocalc = hardcoded command
  src/packages/frontend/frame-editors/frame-tree/title-bar.tsx
  src/packages/frontend/frame-editors/latex-editor/actions.ts
  src/packages/frontend/frame-editors/latex-editor/build-command.tsx
  src/packages/frontend/frame-editors/latex-editor/build.tsx
  src/packages/frontend/frame-editors/latex-editor/editor.ts
  src/packages/frontend/frame-editors/latex-editor/latexmk.ts
Labels: PR-needs review

#5930 next/store: fix min floor of price for small boost subscriptions
  src/packages/util/licenses/purchase/compute-cost.ts
Labels: P-high, PR-needs review

#5926 cleaning up purchase options page
  src/packages/frontend/account/upgrades/upgrades-page.tsx
  src/packages/frontend/billing/billing-page.tsx
  src/packages/frontend/billing/subscription-list.tsx
  src/packages/frontend/project/explorer/explorer.tsx
  src/packages/frontend/site-licenses/purchase/purchase-method.tsx
  src/packages/frontend/site-licenses/purchase/quota-editor.tsx
  src/packages/next/components/billing/layout.tsx
  src/packages/next/components/licenses/layout.tsx
Labels: PR-needs review

#5934 work in progress implementing proper support for reference links
  src/packages/frontend/editors/slate/elements/link/editable.tsx
  src/packages/frontend/editors/slate/elements/references/editable.tsx
  src/packages/frontend/editors/slate/elements/references/index.tsx
  src/packages/frontend/editors/slate/elements/references/type.ts
  src/packages/frontend/editors/slate/elements/types-ssr.ts
  src/packages/frontend/editors/slate/elements/types.ts
  src/packages/frontend/editors/slate/markdown-to-slate/parse-markdown.ts
  src/packages/frontend/editors/slate/markdown-to-slate/parse.ts
  src/packages/frontend/editors/slate/markdown-to-slate/types.ts
  src/packages/frontend/editors/slate/slate-to-markdown.ts
Labels: PR-work in progress

#5942 npm build: check if npm is at least version 8
  src/workspaces.py
Labels: PR-needs review

#5951 hub/next: sort out and document /auth/* endpoint handling
  src/packages/hub/auth.ts
  src/packages/next/pages/auth/ROUTING.md
  src/packages/next/pages/auth/password-reset.tsx
  src/packages/next/pages/auth/password-reset/[id].tsx
  src/packages/next/pages/auth/sign-in.tsx
  src/packages/next/pages/auth/sign-up.tsx
  src/packages/next/pages/auth/try.tsx
  src/packages/next/pages/auth/verify/[token].tsx
Labels: PR-needs review

#5950 next/server: fix email setup
  src/packages/server/email/send-email.ts
  src/packages/server/email/smtp.ts
Labels: PR-needs review
