Repository sagemathinc/cocalc, pull requests merged in 2022-09, with the labels that each got.

#6100 /metrics is disabled (used internally, blocked externally)
  src/packages/util/db-schema/name-rules.ts
Labels: PR-needs review

#6069 next/store: fix off-by-one corner case
  src/packages/next/components/misc/date-range.tsx
  src/packages/next/components/misc/timestamp.tsx
  src/packages/next/components/store/add-box.tsx
  src/packages/next/components/store/boost.tsx
  src/packages/next/components/store/cart.tsx
  src/packages/next/components/store/checkout.tsx
  src/packages/next/components/store/compute-cost.ts
  src/packages/next/components/store/dedicated.tsx
  src/packages/next/components/store/other-items.tsx
  src/packages/next/components/store/site-license-cost.tsx
  src/packages/next/components/store/site-license.tsx
  src/packages/next/components/store/usage-and-duration.tsx
  src/packages/next/components/store/util.ts
  src/packages/server/licenses/purchase/create-license.ts
  src/packages/util/stripe/timecalcs.ts
  src/packages/util/types/store.ts
Labels: PR-needs review

#6103 frontend connecting: user might have to sign in
  src/packages/frontend/app/active-content.tsx
  src/packages/frontend/app/page.tsx
Labels: PR-needs review

#6104 next.js/express.js: disable X-Powered-By everywhere
  src/packages/hub/servers/express-app.ts
  src/packages/next/next.config.js
  src/packages/project/http-api/server.ts
  src/packages/project/servers/browser/http-server.ts
Labels: PR-needs review

#6105 next/billing+licenses: streamlining the layout similar to "store"
  src/packages/next/components/billing/layout.tsx
  src/packages/next/components/billing/menu.tsx
  src/packages/next/components/billing/overview.tsx
  src/packages/next/components/billing/payment-methods.tsx
  src/packages/next/components/licenses/layout.tsx
  src/packages/next/components/licenses/menu.tsx
  src/packages/next/components/licenses/overview.tsx
  src/packages/next/components/statistics/index.tsx
  src/packages/next/components/store/index.tsx
  src/packages/next/components/store/menu.tsx
  src/packages/next/components/store/overview.tsx
  src/packages/next/lib/styles/layouts.tsx
  src/packages/next/pages/billing/[[...page]].tsx
  src/packages/next/pages/licenses/[[...page]].tsx
  src/packages/next/pages/policies/accessibility.tsx
  src/packages/next/pages/store/[[...page]].tsx
Labels: PR-needs review

#6121 util/compute-images: adding 2022-08-17
  src/packages/util/compute-images.ts
Labels: PR-needs review

#6120 Tasks highlight active search
  src/packages/frontend/editors/task-editor/editor.tsx
  src/packages/frontend/editors/task-editor/find.tsx
  src/packages/frontend/editors/task-editor/hashtag-bar.tsx
Labels: PR-needs review

#6106 next/store: bar at the top to always show the price while adjusting options
  src/packages/next/components/misc/timestamp.tsx
  src/packages/next/components/store/add-box.tsx
  src/packages/next/components/store/add-to-cart.tsx
  src/packages/next/components/store/boost.tsx
  src/packages/next/components/store/cart.tsx
  src/packages/next/components/store/cost-info-bar.tsx
  src/packages/next/components/store/dedicated.tsx
  src/packages/next/components/store/site-license-cost.tsx
  src/packages/next/components/store/site-license.tsx
  src/packages/next/components/store/util.ts
  src/packages/next/lib/use-scroll-y.tsx
  src/packages/util/consts/site-license.ts
  src/packages/util/licenses/describe-quota.ts
  src/packages/util/upgrades/utils.ts
Labels: PR-needs review

#6126 util/compute_images: add entry for 22.04 testing
  src/packages/util/compute-images.ts
Labels: PR-needs review

#6131 update JAMS link
  src/packages/next/pages/policies/privacy.tsx
Labels: PR-needs review, A-static

#6133 onprem: license quota to make /ext read/writeable
  src/packages/frontend/admin/page.tsx
  src/packages/frontend/site-licenses/admin/actions.ts
  src/packages/frontend/site-licenses/admin/component.tsx
  src/packages/frontend/site-licenses/admin/license.tsx
  src/packages/frontend/site-licenses/admin/quota.tsx
  src/packages/frontend/site-licenses/admin/store.ts
  src/packages/frontend/site-licenses/purchase/quota-editor.tsx
  src/packages/util/types/site-licenses.ts
Labels: PR-needs review

#6135 onprem: load SSO configs via a file
  src/packages/database/postgres/load-sso-conf.ts
  src/packages/hub/auth.ts
  src/packages/server/auth/sso/types.ts
  src/scripts/auth/gen-sso.py
Labels: PR-needs review

#6136 store: associated a license with a specific project
  src/packages/next/components/store/add-to-cart.tsx
  src/packages/next/components/store/apply-license-to-project.tsx
  src/packages/next/components/store/boost.tsx
  src/packages/next/components/store/cart.tsx
  src/packages/next/components/store/checkout.tsx
  src/packages/next/components/store/congrats.tsx
  src/packages/next/components/store/dedicated.tsx
  src/packages/next/components/store/site-license.tsx
  src/packages/next/components/store/util.ts
  src/packages/next/pages/api/v2/projects/public-path-license.ts
  src/packages/next/pages/api/v2/shopping/cart/add.ts
  src/packages/server/projects/control/util.ts
  src/packages/server/shopping/cart/add.ts
  src/packages/server/shopping/cart/checkout.ts
  src/packages/util/db-schema/shopping-cart-items.ts
Labels: PR-needs review

#6146 store: public prices
  src/packages/next/components/auth/in-place-sign-in-or-up.tsx
  src/packages/next/components/store/add-box.tsx
  src/packages/next/components/store/boost.tsx
  src/packages/next/components/store/cost-info-bar.tsx
  src/packages/next/components/store/dedicated.tsx
  src/packages/next/components/store/index.tsx
  src/packages/next/components/store/sign-in-to-purchase.tsx
  src/packages/next/components/store/site-license.tsx
  src/packages/next/components/store/store-inplace-signup.tsx
  src/packages/next/lib/hooks/profile.ts
Labels: PR-needs review

#6147 store: suppress silly warning
  src/packages/next/components/store/util.ts
Labels: PR-needs review, PR-easy

#6149 frontend: replace "Buy a license" button in project settings with link to store
  src/packages/frontend/project/settings/site-license.tsx
  src/packages/frontend/site-licenses/purchase/buy-license-for-project.tsx
Labels: PR-needs review

#6145 store: url encode form settings
  src/packages/next/components/store/boost.tsx
  src/packages/next/components/store/dedicated.tsx
  src/packages/next/components/store/quota-config.tsx
  src/packages/next/components/store/quota-query-params.ts
  src/packages/next/components/store/run-limit.tsx
  src/packages/next/components/store/site-license.tsx
  src/packages/util/upgrade-spec.js
  src/packages/util/upgrades/consts.ts
  src/packages/util/upgrades/dedicated.ts
Labels: PR-needs review
