Repository sagemathinc/cocalc, pull requests merged in 2022-03, with the labels that each got.

#5768 Next license scrollbars
  src/packages/next/components/licenses/how-used.tsx
  src/packages/next/components/licenses/managed.tsx
Labels: PR-needs review, PR-easy

#5769 jupyter: maybe fix a "TypeError: Cannot read properties of undefined
  src/packages/frontend/jupyter/output-messages/mime-types/register.ts
Labels: PR-needs review

#5723 site-licenses: longer idle timeout
  .vscode/settings.json
  src/packages/assets/package-lock.json
  src/packages/assets/package.json
  src/packages/backend/package-lock.json
  src/packages/backend/package.json
  src/packages/cdn/package-lock.json
  src/packages/cdn/package.json
  src/packages/database/package-lock.json
  src/packages/database/package.json
  src/packages/database/postgres/site-license/hook.ts
  src/packages/frontend/account/licenses/util.ts
  src/packages/frontend/billing/explain-course-licenses.tsx
  src/packages/frontend/billing/store.ts
  src/packages/frontend/billing/subscription-licenses.tsx
  src/packages/frontend/package-lock.json
  src/packages/frontend/package.json
  src/packages/frontend/project/history/types.ts
  src/packages/frontend/projects/actions.ts
  src/packages/frontend/projects/store.ts
  src/packages/frontend/site-licenses/admin/actions.ts
  src/packages/frontend/site-licenses/admin/license.tsx
  src/packages/frontend/site-licenses/admin/quota.tsx
  src/packages/frontend/site-licenses/admin/types.ts
  src/packages/frontend/site-licenses/purchase/purchase.tsx
  src/packages/frontend/site-licenses/purchase/quota-editor.tsx
  src/packages/frontend/site-licenses/site-license-public-info.tsx
  src/packages/frontend/site-licenses/types.ts
  src/packages/hub/package-lock.json
  src/packages/hub/package.json
  src/packages/next/components/store/cart.tsx
  src/packages/next/components/store/site-license-cost.tsx
  src/packages/next/components/store/site-license.tsx
  src/packages/next/package-lock.json
  src/packages/next/package.json
  src/packages/server/licenses/purchase/charge.ts
  src/packages/server/licenses/purchase/create-license.ts
  src/packages/server/licenses/purchase/index.ts
  src/packages/server/package-lock.json
  src/packages/server/package.json
  src/packages/server/projects/control/single-user.ts
  src/packages/server/shopping/cart/checkout.ts
  src/packages/static/package-lock.json
  src/packages/static/package.json
  src/packages/sync/package-lock.json
  src/packages/sync/package.json
  src/packages/util/consts/site-license.ts
  src/packages/util/db-schema/shopping-cart-items.ts
  src/packages/util/db-schema/site-licenses.ts
  src/packages/util/licenses/purchase/util.ts
  src/packages/util/package-lock.json
  src/packages/util/package.json
  src/packages/util/smc-version.js
  src/packages/util/test/quota.test.ts
  src/packages/util/types/dedicated.ts
  src/packages/util/upgrades/dedicated.ts
  src/packages/util/upgrades/quota.ts
  src/update_version
Labels: PR-work in progress

#5780 fix switching latex deps
  src/packages/frontend/frame-editors/code-editor/actions.ts
  src/packages/frontend/frame-editors/code-editor/codemirror-editor.tsx
  src/packages/frontend/frame-editors/frame-tree/leaf.tsx
  src/packages/frontend/frame-editors/latex-editor/actions.ts
  src/packages/frontend/frame-editors/latex-editor/errors-and-warnings.tsx
  src/packages/project/browser-websocket/api.ts
  src/packages/project/browser-websocket/canonical-path.ts
Labels: needs-help

#5770 Course edtior react.fc
  src/packages/frontend/course/assignments/actions.ts
  src/packages/frontend/course/assignments/assignment-student-list.tsx
  src/packages/frontend/course/assignments/assignment.tsx
  src/packages/frontend/course/assignments/assignments-panel.tsx
  src/packages/frontend/course/assignments/configure-peer.tsx
  src/packages/frontend/course/assignments/consts.ts
  src/packages/frontend/course/assignments/skip.tsx
  src/packages/frontend/course/common.tsx
  src/packages/frontend/course/common/FoldersToolBar.tsx
  src/packages/frontend/course/common/big-time.tsx
  src/packages/frontend/course/common/consts.ts
  src/packages/frontend/course/common/flex-panel.tsx
  src/packages/frontend/course/common/folders-tool-bar.tsx
  src/packages/frontend/course/common/index.ts
  src/packages/frontend/course/common/multiple-add-search.tsx
  src/packages/frontend/course/common/progress.tsx
  src/packages/frontend/course/common/student-assignment-info-header.tsx
  src/packages/frontend/course/common/student-assignment-info.tsx
  src/packages/frontend/course/configuration/nbgrader.tsx
  src/packages/frontend/course/configuration/terminal-command.tsx
  src/packages/frontend/course/configuration/upgrades.tsx
  src/packages/frontend/course/handouts/handout-info-header.tsx
  src/packages/frontend/course/handouts/handout-student-list.tsx
  src/packages/frontend/course/handouts/handout.tsx
  src/packages/frontend/course/handouts/handouts-info-panel.tsx
  src/packages/frontend/course/handouts/handouts-panel.tsx
  src/packages/frontend/course/nbgrader/scores.tsx
  src/packages/frontend/course/shared-project/delete-shared-project.tsx
  src/packages/frontend/course/shared-project/shared-project-panel.tsx
  src/packages/frontend/course/student-projects/actions.ts
  src/packages/frontend/course/student-projects/run-in-all-projects.ts
  src/packages/frontend/course/students/students-panel-student.tsx
  src/packages/frontend/course/students/students-panel.tsx
  src/packages/frontend/course/util.ts
  src/packages/frontend/frame-editors/course-editor/course-panel-wrapper.tsx
  src/packages/frontend/frame-editors/course-editor/course-panels.ts
  src/packages/frontend/frame-editors/course-editor/course-tab-bar.tsx
  src/packages/frontend/frame-editors/course-editor/overview/overview.tsx
  src/packages/frontend/jupyter/nbgrader/actions.ts
Labels: PR-needs review

#5777 Fix some typos in subset of src/packages
  src/packages/assets/README.md
  src/packages/assets/misc/talk-20121004/index.html
  src/packages/assets/term/term.js
  src/packages/assets/threejs/r73/OrbitControls.js
  src/packages/backend/execute-code.coffee
  src/packages/backend/logger.ts
  src/packages/backend/package-lock.json
  src/packages/backend/test/misc_node-test.coffee
  src/packages/database/postgres-base.coffee
  src/packages/database/postgres-blobs.coffee
  src/packages/database/postgres-ops.coffee
  src/packages/database/postgres-server-queries.coffee
  src/packages/database/postgres-user-queries.coffee
  src/packages/database/postgres/collab.ts
  src/packages/database/postgres/delete-projects.ts
  src/packages/database/postgres/site-license/hook.ts
  src/packages/database/postgres/site-license/search.ts
  src/packages/database/postgres/site-license/usage-log.ts
  src/packages/next/components/account/config/account/delete-account.tsx
  src/packages/next/components/account/config/account/name.tsx
  src/packages/next/components/account/config/editor/jupyter.tsx
  src/packages/next/components/landing/backups.tsx
  src/packages/next/components/landing/compare.json
  src/packages/next/lib/share/get-public-path-info.ts
  src/packages/next/pages/api/v2/accounts/sign-out.ts
  src/packages/next/pages/api/v2/shopping/cart/recent-purchases.ts
  src/packages/next/pages/features/linux.tsx
  src/packages/next/pages/features/r-statistical-software.tsx
  src/packages/next/pages/features/sage.tsx
  src/packages/next/pages/features/whiteboard.tsx
Labels: PR-needs review

#5778 Add missing semicolons (fixes recommendations from LGTM)
  src/packages/assets/misc/talk-20121004/ui/default/slides.js
  src/packages/assets/threejs/r73/CanvasRenderer.js
  src/packages/assets/threejs/r73/OrbitControls.js
  src/packages/assets/threejs/r73/Projector.js
  src/packages/frontend/course/shared-project/actions.ts
  src/packages/server/projects/control/util.ts
Labels: PR-needs review

#5787 Less intimidating trial banner
  src/packages/frontend/project/settings/site-license.tsx
  src/packages/frontend/project/trial-banner.tsx
  src/packages/frontend/site-licenses/input.tsx
  src/packages/frontend/site-licenses/select-license.tsx
Labels: PR-needs review

#5775 expose run quotas in project settings + usage
  src/packages/database/package-lock.json
  src/packages/database/package.json
  src/packages/database/postgres-server-queries.coffee
  src/packages/frontend/account/ssh-keys/fingerprint.ts
  src/packages/frontend/account/ssh-keys/global-ssh-keys.tsx
  src/packages/frontend/account/ssh-keys/ssh-key-list.tsx
  src/packages/frontend/components/index.tsx
  src/packages/frontend/components/nowrap.tsx
  src/packages/frontend/components/question-mark-text.tsx
  src/packages/frontend/components/setting-box.tsx
  src/packages/frontend/components/time-ago.tsx
  src/packages/frontend/components/tip.tsx
  src/packages/frontend/components/upgrade-adjustor.tsx
  src/packages/frontend/course/configuration/upgrades.tsx
  src/packages/frontend/customize.tsx
  src/packages/frontend/package-lock.json
  src/packages/frontend/package.json
  src/packages/frontend/project/page/project-status-hook.ts
  src/packages/frontend/project/settings/body.tsx
  src/packages/frontend/project/settings/quota-console.tsx
  src/packages/frontend/project/settings/run-quota/components.tsx
  src/packages/frontend/project/settings/run-quota/hooks.tsx
  src/packages/frontend/project/settings/run-quota/index.ts
  src/packages/frontend/project/settings/run-quota/misc.ts
  src/packages/frontend/project/settings/run-quota/run-quota.tsx
  src/packages/frontend/project/settings/settings.tsx
  src/packages/frontend/project/settings/site-license.tsx
  src/packages/frontend/project/settings/ssh.tsx
  src/packages/frontend/project/settings/upgrade-usage.tsx
  src/packages/hub/package-lock.json
  src/packages/hub/package.json
  src/packages/project/package-lock.json
  src/packages/project/package.json
  src/packages/project/project-status/const.ts
  src/packages/project/project-status/server.ts
  src/packages/project/project-status/types.ts
  src/packages/project/project-status/utils.ts
  src/packages/server/package-lock.json
  src/packages/server/package.json
  src/packages/server/projects/control/stop-idle-projects.ts
  src/packages/static/package-lock.json
  src/packages/static/package.json
  src/packages/util/db-schema/projects.ts
  src/packages/util/db-schema/site-defaults.ts
  src/packages/util/package-lock.json
  src/packages/util/package.json
  src/packages/util/upgrades/quota.ts
Labels: PR-needs review

#5789 frontend/course: fix sorting students
  src/packages/frontend/course/students/students-panel.tsx
Labels: PR-needs review

#5799 jupyter/nbconvert: increase timeout
  src/packages/project/jupyter/convert/index.ts
Labels: PR-needs review

#5793 next: fix how software env is processed
  src/packages/next/components/landing/executables-table.tsx
  src/packages/next/components/landing/julia-libraries.tsx
  src/packages/next/components/landing/octave-libraries.tsx
  src/packages/next/components/landing/python-libraries.tsx
  src/packages/next/components/landing/r-libraries.tsx
  src/packages/next/components/landing/software-libraries.tsx
  src/packages/next/lib/landing/executables.ts
  src/packages/next/lib/landing/get-libraries.ts
  src/packages/next/lib/landing/libraries.ts
  src/packages/next/lib/landing/software-specs.ts
  src/packages/next/lib/landing/types.ts
  src/packages/next/package-lock.json
  src/packages/next/package.json
  src/packages/next/pages/software/executables.tsx
  src/packages/next/pages/software/index.tsx
  src/packages/next/pages/software/julia.tsx
  src/packages/next/pages/software/octave.tsx
  src/packages/next/pages/software/python.tsx
  src/packages/next/pages/software/r.tsx
Labels: PR-needs review

#5798 frontend/latex: fix rnw/Rnw synctex processing and a typo
  src/packages/frontend/frame-editors/latex-editor/actions.ts
  src/packages/frontend/frame-editors/latex-editor/synctex.ts
Labels: PR-needs review

#5792 Join method from path module should not be used for joining URIs part…
  src/packages/frontend/collaborators/project-invite-tokens.tsx
Labels: PR-needs work, PR-needs review

#5813 next/software: be more careful
  src/packages/next/lib/landing/get-libraries.ts
  src/packages/next/lib/landing/types.ts
Labels: PR-needs review, PR-easy

#5811 db/syncstrings: just whitespace to fix the indentation
  src/packages/database/postgres-blobs.coffee
Labels: PR-needs review, PR-easy

#5816 fix license related issues
  src/packages/database/postgres/site-license/sync-subscriptions.ts
  src/packages/frontend/account/licenses/managed-licenses.tsx
  src/packages/frontend/site-licenses/admin/license.tsx
  src/packages/frontend/site-licenses/purchase/quota-editor.tsx
  src/packages/frontend/site-licenses/site-license-public-info.tsx
  src/packages/next/components/licenses/license.tsx
  src/packages/util/db-schema/site-licenses.ts
Labels: PR-needs review
