Repository sagemathinc/cocalc, pull requests merged in 2024-01, with the labels that each got.

#7159 lodash and @types/lodash
  src/packages/database/package.json
  src/packages/frontend/package.json
  src/packages/hub/package.json
  src/packages/pnpm-lock.yaml
  src/packages/project/package.json
  src/packages/server/auth/sso/passport-login.ts
  src/packages/server/hub/auth.ts
  src/packages/server/package.json
  src/packages/sync/package.json
  src/packages/terminal/package.json
  src/packages/util/package.json
Labels: PR-needs review

#7174 7150: Added balance refresh to `PurchasesTable` refresh handler.
  src/package.json
  src/packages/frontend/purchases/purchases.tsx
  src/packages/hub/package.json
Labels: PR-work in progress

#7178 #7161: Fixed subscription cancel/resume logic when computing cost to resume or cancel an existing subscription.
  src/packages/next/pages/api/v2/purchases/cancel-subscription.ts
  src/packages/server/purchases/cancel-subscription.ts
  src/packages/server/purchases/edit-license.ts
  src/packages/server/purchases/maintain-subscriptions.ts
  src/packages/server/purchases/resume-subscription.test.ts
  src/packages/util/consts/billing.ts
  src/packages/util/licenses/purchase/compute-cost.ts
  src/packages/util/purchases/cost-to-edit-license.ts
  src/packages/util/purchases/current-license-value.ts
Labels: PR-work in progress, PR-need feedback

#7182 fix bugs in purchasing
  src/packages/next/components/store/checkout.tsx
  src/packages/server/purchases/purchase-shopping-cart-item.test.ts
  src/packages/server/purchases/purchase-shopping-cart-item.ts
  src/packages/util/licenses/purchase/compute-cost.ts
  src/packages/util/licenses/purchase/consts.ts
  src/packages/util/purchases/cost-to-edit-license.ts
Labels: PR-work in progress

#7184 frontend/flyout/files: duplicate controls at the top
  src/packages/frontend/project/page/flyouts/consts.ts
  src/packages/frontend/project/page/flyouts/files-bottom.tsx
  src/packages/frontend/project/page/flyouts/files-controls.tsx
  src/packages/frontend/project/page/flyouts/files-header.tsx
  src/packages/frontend/project/page/flyouts/files-select-extra.tsx
  src/packages/frontend/project/page/flyouts/files.tsx
  src/packages/frontend/project/page/flyouts/utils.ts
Labels: PR-needs review

#7200 frontend/flyout/files: show top buttons when file is selected
  src/packages/frontend/project/page/flyouts/files-controls.tsx
  src/packages/frontend/project/page/flyouts/files-select-extra.tsx
Labels: PR-needs review

#7203 share dialog: various layout improvements
  src/packages/frontend/components/copy-to-clipboard.tsx
  src/packages/frontend/share/config.tsx
  src/packages/frontend/share/configure-name.tsx
Labels: PR-needs review

#7205 #6919: Added user balance to store navbar when user is logged in.
  src/packages/next/components/store/checkout.tsx
  src/packages/next/components/store/index.tsx
  src/packages/next/components/store/menu.tsx
  src/packages/next/components/store/vouchers.tsx
  src/packages/next/lib/balance.ts
Labels: PR-work in progress

#7208 frontend/flyout: tweak col alignments
  src/packages/frontend/project/page/flyouts/active.tsx
  src/packages/frontend/project/page/flyouts/file-list-item.tsx
Labels: PR-needs review

#7209 flyout/log: showuser, filters, etc.
  src/packages/frontend/components/icon.tsx
  src/packages/frontend/project/history/log-entry.tsx
  src/packages/frontend/project/page/flyouts/header.tsx
  src/packages/frontend/project/page/flyouts/log-header.tsx
  src/packages/frontend/project/page/flyouts/log.tsx
  src/packages/frontend/project/page/flyouts/state.ts
  src/packages/frontend/project/page/flyouts/utils.ts
  src/packages/frontend/project_actions.ts
  src/packages/frontend/project_store.ts
Labels: PR-needs review

#7216 frontend/flyout/new: various fixes
  src/packages/frontend/project/page/flyouts/new.tsx
Labels: PR-needs review

#7222 server/llm/gemini: update lib and optionally throw error
  src/packages/pnpm-lock.yaml
  src/packages/server/llm/index.ts
  src/packages/server/package.json
Labels: PR-needs review
