Repository sagemathinc/cocalc, pull requests merged in 2024-07, with the labels that each got.

#7653 frontend/slides: fix wrongly aligned icons
  src/packages/frontend/frame-editors/whiteboard-editor/delete-page.tsx
  src/packages/frontend/frame-editors/whiteboard-editor/new-page.tsx
  src/packages/frontend/frame-editors/whiteboard-editor/overview.tsx
  src/packages/frontend/frame-editors/whiteboard-editor/pages.tsx
Labels: PR-needs review

#7657 rename "CoCalc Cloud" → "CoCalc OnPrem"
  src/packages/database/postgres/site-license/hook.ts
  src/packages/database/postgres/site-license/quota-site-settings.ts
  src/packages/frontend/compute/onprem-config.tsx
  src/packages/frontend/course/configuration/envvars-config.tsx
  src/packages/frontend/course/configuration/student-project-software-environment.tsx
  src/packages/frontend/project/settings/datastore.tsx
  src/packages/next/components/landing/cocalc-com-features.tsx
  src/packages/next/pages/auth/ROUTING.md
  src/packages/next/pages/pricing/onprem.tsx
  src/packages/util/quota.test.ts
  src/packages/util/upgrades/consts.ts
  src/packages/util/upgrades/quota.ts
Labels: PR-needs review

#7643 llm/abuse improvements
  src/packages/server/llm/abuse.ts
Labels: PR-needs review

#7656 free project limitation
  src/packages/frontend/customize.tsx
  src/packages/frontend/editors/stopwatch/stopwatch.tsx
  src/packages/frontend/project/trial-banner.tsx
  src/packages/frontend/site-licenses/purchase/buy-license-for-project.tsx
  src/packages/util/consts/billing.ts
  src/packages/util/db-schema/site-defaults.ts
Labels: PR-work in progress

#7681 frontend/trial-banner: tweak tracking
  src/packages/frontend/project/trial-banner.tsx
Labels: PR-needs review

#7689 frontend/trial-banner: fix typo by removing VC from the text
  src/packages/frontend/project/trial-banner.tsx
Labels: PR-needs review

#7686 async project exec
  src/packages/backend/execute-code.test.ts
  src/packages/backend/execute-code.ts
  src/packages/next/lib/api/schema/exec.ts
  src/packages/next/pages/api/v2/exec.ts
  src/packages/project/exec_shell_code.test.ts
  src/packages/project/exec_shell_code.ts
  src/packages/util/aggregate.d.ts
  src/packages/util/aggregate.ts
  src/packages/util/message.js
  src/packages/util/types/execute-code.ts
Labels: PR-needs review

#7696 tex/rmd/qmd: "build on save" toggle button
  src/packages/frontend/account/editor-settings/checkboxes.tsx
  src/packages/frontend/components/icon.tsx
  src/packages/frontend/frame-editors/code-editor/actions.ts
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/frame-editors/latex-editor/editor.ts
  src/packages/frontend/frame-editors/qmd-editor/actions.ts
  src/packages/frontend/frame-editors/qmd-editor/editor.ts
  src/packages/frontend/frame-editors/rmd-editor/actions.ts
  src/packages/frontend/frame-editors/rmd-editor/editor.ts
Labels: PR-needs review

#7695 gpt-4o-mini
  src/packages/package.json
  src/packages/pnpm-lock.yaml
  src/packages/server/llm/index.ts
  src/packages/server/llm/test/00.test.ts
  src/packages/server/package.json
  src/packages/util/db-schema/llm-utils.ts
  src/packages/util/db-schema/purchase-quotas.ts
Labels: PR-needs review

#7699 npm: updating typescript and ts-jest
  src/compute/compute/package.json
  src/packages/package.json
  src/packages/pnpm-lock.yaml
  src/packages/static/package.json
  src/packages/sync/package.json
Labels: PR-needs review

#7708 api/async exec: collect process stats
  src/packages/backend/execute-code.test.ts
  src/packages/backend/execute-code.ts
  src/packages/backend/package.json
  src/packages/backend/process-stats.ts
  src/packages/comm/project-status/utils.ts
  src/packages/frontend/frame-editors/generic/client.ts
  src/packages/frontend/project/info/components.tsx
  src/packages/frontend/project/info/flyout.tsx
  src/packages/frontend/project/info/full.tsx
  src/packages/frontend/project/info/project-info.tsx
  src/packages/frontend/project/info/types.ts
  src/packages/frontend/project/info/utils.ts
  src/packages/next/lib/api/schema/exec.ts
  src/packages/next/pages/api/v2/exec.ts
  src/packages/project/autorenice.ts
  src/packages/project/exec_shell_code.ts
  src/packages/project/project-info/project-info.ts
  src/packages/project/project-info/server.ts
  src/packages/project/project-info/utils.ts
  src/packages/project/project-status/server.ts
  src/packages/project/sync/project-info.ts
  src/packages/project/usage-info/server.ts
  src/packages/util/consts/project.ts
  src/packages/util/message.js
  src/packages/util/types/execute-code.ts
  src/packages/util/types/project-info/types.ts
Labels: PR-needs review

#7711 Update Refunds section in ToS
  src/packages/next/pages/policies/terms.tsx
Labels: PR-needs trivial work

#7723 sagews: python 3.12 compatibility
  src/smc_sagews/setup.py
  src/smc_sagews/smc_sagews/sage_salvus.py
  src/smc_sagews/smc_sagews/sage_server.py
Labels: PR-needs review
