Repository sagemathinc/cocalc, pull requests merged in 2024-08, with the labels that each got.

#7736 frontend/explorer/search: get rid of react-bootstrap Alert
  src/packages/frontend/antd-bootstrap.tsx
  src/packages/frontend/project/ask-filename.tsx
  src/packages/frontend/project/explorer/search-bar.tsx
Labels: PR-needs review

#7745 Fix Issue 5991
  src/packages/frontend/editors/slate/elements/codemirror.tsx
  src/packages/frontend/jupyter/cell-list.tsx
  src/packages/frontend/jupyter/output-messages/cached-iframe.tsx
  src/packages/frontend/jupyter/output-messages/iframe.tsx
  src/packages/frontend/jupyter/output-messages/javascript.tsx
  src/packages/frontend/jupyter/output-messages/message.tsx
  src/packages/frontend/jupyter/output-messages/mime-types/html.tsx
  src/packages/frontend/jupyter/output-messages/mime-types/iframe.tsx
  src/packages/frontend/jupyter/output-messages/mime-types/register.ts
  src/packages/frontend/jupyter/output-messages/stable-unsafe-html.tsx
  src/packages/frontend/package.json
  src/packages/jupyter/blobs/iframe.ts
  src/packages/pnpm-lock.yaml
Labels: PR-work in progress

#7752 extract project/backend aspects of api-exec-await
  src/packages/backend/execute-code.test.ts
  src/packages/backend/execute-code.ts
  src/packages/frontend/client/project.ts
  src/packages/frontend/frame-editors/generic/client.ts
  src/packages/frontend/frame-editors/latex-editor/actions.ts
  src/packages/frontend/frame-editors/latex-editor/build.tsx
  src/packages/frontend/frame-editors/latex-editor/errors-and-warnings.tsx
  src/packages/frontend/frame-editors/latex-editor/hooks.ts
  src/packages/frontend/frame-editors/latex-editor/knitr.ts
  src/packages/frontend/frame-editors/latex-editor/latex-log-parser.ts
  src/packages/frontend/frame-editors/latex-editor/pythontex.ts
  src/packages/frontend/frame-editors/latex-editor/sagetex.ts
  src/packages/frontend/frame-editors/latex-editor/types.ts
  src/packages/frontend/frame-editors/pdf-editor/actions.ts
  src/packages/next/lib/api/schema/exec.ts
  src/packages/next/pages/api/v2/exec.ts
  src/packages/next/pages/api/v2/index.ts
  src/packages/pnpm-lock.yaml
  src/packages/server/projects/connection/handle-message.ts
  src/packages/util/consts/project.ts
  src/packages/util/db-schema/projects.ts
  src/packages/util/misc.test.ts
  src/packages/util/misc.ts
  src/packages/util/types/execute-code.ts
Labels: PR-needs review

#7765 Fix Project Collaborator Permission Check
  src/packages/next/pages/api/v2/projects/copy-path.ts
  src/packages/next/pages/api/v2/projects/copy-url.ts
  src/packages/next/pages/api/v2/projects/start.ts
  src/packages/next/pages/api/v2/projects/stop.ts
  src/packages/next/pages/api/v2/projects/touch.ts
  src/packages/server/jupyter/execute.ts
  src/packages/server/jupyter/kernels.ts
Labels: PR-needs review

#7722 api/exec await + latex
  src/packages/backend/execute-code.ts
  src/packages/frontend/editors/stopwatch/time.tsx
  src/packages/frontend/frame-editors/_style.sass
  src/packages/frontend/frame-editors/code-editor/actions.ts
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/frame-editors/frame-tree/title-bar.tsx
  src/packages/frontend/frame-editors/latex-editor/actions.ts
  src/packages/frontend/frame-editors/latex-editor/bibtex.ts
  src/packages/frontend/frame-editors/latex-editor/build.tsx
  src/packages/frontend/frame-editors/latex-editor/constants.ts
  src/packages/frontend/frame-editors/latex-editor/editor.ts
  src/packages/frontend/frame-editors/latex-editor/errors-and-warnings.tsx
  src/packages/frontend/frame-editors/latex-editor/gutters.tsx
  src/packages/frontend/frame-editors/latex-editor/hooks.ts
  src/packages/frontend/frame-editors/latex-editor/knitr.ts
  src/packages/frontend/frame-editors/latex-editor/latexmk.ts
  src/packages/frontend/frame-editors/latex-editor/pdf-embed.tsx
  src/packages/frontend/frame-editors/latex-editor/pdfjs-doc-cache.ts
  src/packages/frontend/frame-editors/latex-editor/pdfjs.tsx
  src/packages/frontend/frame-editors/latex-editor/pythontex.ts
  src/packages/frontend/frame-editors/latex-editor/sagetex.ts
  src/packages/frontend/frame-editors/latex-editor/util.ts
  src/packages/frontend/frame-editors/pdf-editor/actions.ts
  src/packages/frontend/frame-editors/rmd-editor/build-log.tsx
  src/packages/sync/client/call.ts
  src/packages/util/types/execute-code.ts
Labels: PR-needs review

#7762 Account Management API: Added v2 API endpoint to list project collaborators…
  src/packages/next/components/project/project.tsx
  src/packages/next/components/share/collaborators.tsx
  src/packages/next/lib/api/schema/projects/collaborators/list.ts
  src/packages/next/lib/share/get-collaborators.ts
  src/packages/next/lib/share/types.ts
  src/packages/next/pages/api/v2/projects/collaborators/list.ts
Labels: PR-needs review

#7763 next/share: embed PDF
  src/packages/hub/hub.ts
  src/packages/hub/servers/app/next.ts
  src/packages/hub/servers/express-app.ts
  src/packages/next/components/path/path.tsx
  src/packages/next/components/share/file-contents.tsx
  src/packages/next/components/share/path-contents.tsx
  src/packages/next/lib/share/handle-raw.ts
  src/packages/next/lib/share/virtual-hosts.ts
Labels: PR-needs review

#7776 npm updates
  src/compute/compute/package.json
  src/compute/pnpm-lock.yaml
  src/packages/backend/package.json
  src/packages/frontend/editors/slate/elements/details/index.tsx
  src/packages/frontend/editors/slate/elements/image/index.tsx
  src/packages/frontend/editors/slate/markdown-to-slate/util.ts
  src/packages/frontend/misc/process-links/string.ts
  src/packages/frontend/package.json
  src/packages/hub/package.json
  src/packages/next/package.json
  src/packages/pnpm-lock.yaml
  src/packages/project/package.json
  src/packages/server/package.json
  src/packages/server/support/create-ticket.ts
  src/packages/static/package.json
  src/packages/sync-client/package.json
Labels: PR-needs review

#7780 frontend/page: porting over bottom-left vertical bar show/hide changes
  src/packages/frontend/components/icon.tsx
  src/packages/frontend/project/page/content.tsx
  src/packages/frontend/project/page/flyouts/body.tsx
  src/packages/frontend/project/page/flyouts/search.tsx
  src/packages/frontend/project/page/home-page/button.tsx
  src/packages/frontend/project/page/page.tsx
  src/packages/frontend/project/page/project-collaborators.tsx
  src/packages/frontend/project/page/vertical-fixed-tabs.tsx
  src/packages/frontend/project/search/body.tsx
  src/packages/frontend/project/search/header.tsx
  src/packages/frontend/project/search/search.tsx
  src/packages/frontend/project/servers/project-servers.tsx
Labels: PR-needs review

#7788 frontend/frame-editors: nail down type of each frame editor spec + translation fix
  src/packages/frontend/frame-editors/code-editor/editor.ts
  src/packages/frontend/frame-editors/course-editor/editor.ts
  src/packages/frontend/frame-editors/crm-editor/editor.ts
  src/packages/frontend/frame-editors/csv-editor/editor.ts
  src/packages/frontend/frame-editors/frame-tree/frame-tree.tsx
  src/packages/frontend/frame-editors/frame-tree/types.ts
  src/packages/frontend/frame-editors/generic/chat.tsx
  src/packages/frontend/frame-editors/html-editor/editor.ts
  src/packages/frontend/frame-editors/jupyter-editor/editor.ts
  src/packages/frontend/frame-editors/latex-editor/editor.ts
  src/packages/frontend/frame-editors/lean-editor/editor.ts
  src/packages/frontend/frame-editors/markdown-editor/editor.ts
  src/packages/frontend/frame-editors/pdf-editor/editor.ts
  src/packages/frontend/frame-editors/qmd-editor/editor.ts
  src/packages/frontend/frame-editors/rmd-editor/editor.ts
  src/packages/frontend/frame-editors/rst-editor/editor.ts
  src/packages/frontend/frame-editors/sagews-editor/editor.ts
  src/packages/frontend/frame-editors/settings/editor.tsx
  src/packages/frontend/frame-editors/slides-editor/editor.ts
  src/packages/frontend/frame-editors/task-editor/editor.ts
  src/packages/frontend/frame-editors/terminal-editor/editor.ts
  src/packages/frontend/frame-editors/time-travel-editor/editor.ts
  src/packages/frontend/frame-editors/whiteboard-editor/editor.ts
  src/packages/frontend/frame-editors/wiki-editor/editor.ts
  src/packages/frontend/frame-editors/x11-editor/editor.ts
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/de_DE.compiled.json
  src/packages/frontend/i18n/de_DE.json
  src/packages/frontend/i18n/es_ES.compiled.json
  src/packages/frontend/i18n/es_ES.json
  src/packages/frontend/i18n/extracted.json
  src/packages/frontend/i18n/zh_CN.compiled.json
  src/packages/frontend/i18n/zh_CN.json
  src/packages/frontend/jupyter/llm/cell-tool.tsx
Labels: PR-needs review

#7798 frontend/i18n: remove derived files from git
  .gitignore
  src/packages/frontend/i18n/de_DE.compiled.json
  src/packages/frontend/i18n/es_ES.compiled.json
  src/packages/frontend/i18n/extracted.json
  src/packages/frontend/i18n/fr_FR.compiled.json
  src/packages/frontend/i18n/it_IT.compiled.json
  src/packages/frontend/i18n/ru_RU.compiled.json
  src/packages/frontend/i18n/zh_CN.compiled.json
  src/packages/frontend/package.json
  src/packages/project/package.json
Labels: PR-needs testing
