Repository sagemathinc/cocalc, pull requests merged in 2024-09, with the labels that each got.

#7793 frontend/flyout: porting over the project homepage from #6804
  src/packages/frontend/project/page/home-page/index.tsx
  src/packages/frontend/project/page/home-page/recent-files.tsx
Labels: PR-needs review, E-unclear

#7828 I18n: fixes, jupyter, etc.
  .gitignore
  src/packages/frontend/account/account-page.tsx
  src/packages/frontend/account/account-preferences.tsx
  src/packages/frontend/account/editor-settings/autosave-interval.tsx
  src/packages/frontend/account/editor-settings/color-schemes.tsx
  src/packages/frontend/account/editor-settings/editor-settings.tsx
  src/packages/frontend/account/editor-settings/font-size.tsx
  src/packages/frontend/account/editor-settings/indent-size.tsx
  src/packages/frontend/account/settings/email-verification.tsx
  src/packages/frontend/app/localize.tsx
  src/packages/frontend/app/render.tsx
  src/packages/frontend/editors/archive/component.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/frame-editors/jupyter-editor/editor.ts
  src/packages/frontend/i18n/bin/common.sh
  src/packages/frontend/i18n/bin/compile.sh
  src/packages/frontend/i18n/bin/download.sh
  src/packages/frontend/i18n/bin/extract.sh
  src/packages/frontend/i18n/bin/upload.sh
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/i18n.test.ts
  src/packages/frontend/i18n/index.ts
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/extracted.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
  src/packages/frontend/jupyter/about.tsx
  src/packages/frontend/jupyter/cell-buttonbar-menu.tsx
  src/packages/frontend/jupyter/cell-buttonbar.tsx
  src/packages/frontend/jupyter/commands.ts
  src/packages/frontend/jupyter/select-kernel.tsx
  src/packages/frontend/purchases/automatic-payments.tsx
  src/packages/frontend/purchases/refresh.tsx
  src/packages/frontend/purchases/subscriptions.tsx
  src/packages/util/consts/locale.ts
Labels: PR-needs review

#7830 frontend/i18n: fix failing test
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
Labels: PR-needs review

#7829 npm: update express, express-sessions, and express-rate-limit
  src/packages/hub/package.json
  src/packages/next/package.json
  src/packages/pnpm-lock.yaml
  src/packages/project/package.json
  src/packages/server/package.json
Labels: PR-work in progress

#7841 I18n continued …
  src/packages/frontend/collaborators/current-collabs.tsx
  src/packages/frontend/components/loading.tsx
  src/packages/frontend/course/configuration/upgrades.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/format-commands.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
  src/packages/frontend/jupyter/status.tsx
  src/packages/frontend/project/explorer/misc-side-buttons.tsx
  src/packages/frontend/project/explorer/search-bar.tsx
  src/packages/frontend/project/info/index.ts
  src/packages/frontend/project/new/file-type-selector.tsx
  src/packages/frontend/project/new/new-file-dropdown.tsx
  src/packages/frontend/project/new/new-file-page.tsx
  src/packages/frontend/project/page/file-tab.tsx
  src/packages/frontend/project/page/flyouts/collabs.tsx
  src/packages/frontend/project/page/flyouts/files-header.tsx
  src/packages/frontend/project/page/flyouts/header.tsx
  src/packages/frontend/project/page/flyouts/log-header.tsx
  src/packages/frontend/project/page/flyouts/log.tsx
  src/packages/frontend/project/page/flyouts/new.tsx
  src/packages/frontend/project/page/home-page/ai-generate-document.tsx
  src/packages/frontend/project/page/page.tsx
  src/packages/frontend/project/page/project-collaborators.tsx
  src/packages/frontend/project/page/project-licenses.tsx
  src/packages/frontend/project/page/vertical-fixed-tabs.tsx
  src/packages/frontend/project/servers/consts.ts
  src/packages/frontend/project/settings/site-license.tsx
  src/packages/frontend/project/settings/upgrade-usage.tsx
Labels: PR-needs review

#7842 frontend/i18n: fix test, just a missing prefix
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
Labels: PR-needs review

#7840 properly place text in compute server templates
  src/packages/frontend/compute/public-templates.tsx
Labels: PR-needs review

#7839 use filename when creating file via extension dropdown
  src/packages/frontend/project/new/new-file-page.tsx
Labels: PR-positive review

#7835 Restrict student search to use only emails
  src/packages/frontend/client/users.ts
  src/packages/frontend/course/students/actions.ts
  src/packages/frontend/course/students/students-panel.tsx
  src/packages/hub/client.coffee
  src/packages/server/accounts/search.ts
  src/packages/util/message.js
Labels: PR-needs work

#7852 frontend/i18n: cont. translations
  src/packages/frontend/app/page.tsx
  src/packages/frontend/chat/chat-indicator.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/format-commands.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/manage.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/types.ts
  src/packages/frontend/frame-editors/frame-tree/title-bar.tsx
  src/packages/frontend/frame-editors/generic/chat.tsx
  src/packages/frontend/frame-editors/jupyter-editor/editor.ts
  src/packages/frontend/frame-editors/latex-editor/editor.ts
  src/packages/frontend/frame-editors/terminal-editor/editor.ts
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
  src/packages/frontend/project/history/log.tsx
  src/packages/frontend/project/settings/about-box.tsx
  src/packages/frontend/project/settings/hide-delete-box.tsx
  src/packages/frontend/project/settings/restart-project.tsx
  src/packages/frontend/project/settings/site-license.tsx
  src/packages/frontend/site-licenses/site-license-public-info.tsx
Labels: PR-needs review

#7864 frontend/i18n: continue...
  src/packages/frontend/account/account-page.tsx
  src/packages/frontend/account/i18n-selector.tsx
  src/packages/frontend/account/other-settings.tsx
  src/packages/frontend/account/terminal-settings.tsx
  src/packages/frontend/account/types.ts
  src/packages/frontend/app/connection-info.tsx
  src/packages/frontend/app/i18n-banner.tsx
  src/packages/frontend/app/page.tsx
  src/packages/frontend/app/warnings.tsx
  src/packages/frontend/chat/llm-cost-estimation.tsx
  src/packages/frontend/client/project.ts
  src/packages/frontend/components/run-button/index.tsx
  src/packages/frontend/course/configuration/terminal-command.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/frame-editors/llm/llm-selector.tsx
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/index.ts
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
  src/packages/frontend/jupyter/cell-buttonbar.tsx
  src/packages/frontend/jupyter/llm/cell-tool.tsx
  src/packages/frontend/jupyter/nbgrader/actions.ts
  src/packages/frontend/jupyter/select-kernel.tsx
  src/packages/frontend/jupyter/status.tsx
  src/packages/frontend/landing-page/connecting.tsx
  src/packages/frontend/misc/llm-cost-estimation.tsx
  src/packages/frontend/project/call-to-support.tsx
  src/packages/frontend/project/explorer/explorer.tsx
  src/packages/frontend/project/explorer/file-listing/file-listing.tsx
  src/packages/frontend/project/explorer/mini-terminal.tsx
  src/packages/frontend/project/history/log-entry.tsx
  src/packages/frontend/project/open-file.ts
  src/packages/frontend/project/page/flyouts/files-header.tsx
  src/packages/frontend/project/page/home-page/ai-generate-document.tsx
  src/packages/frontend/project/project-start-warning.ts
  src/packages/frontend/project/start-button.tsx
  src/packages/frontend/project_actions.ts
  src/packages/util/consts/locale.ts
Labels: PR-needs review

#7877 frontend/latex: fix "help me fix" in gutter
  src/packages/frontend/frame-editors/latex-editor/gutters.tsx
Labels: PR-needs review

#7878 i18n: more menu entries and notifications
  src/packages/frontend/app/fullscreen-button.tsx
  src/packages/frontend/compute/menu.tsx
  src/packages/frontend/frame-editors/frame-tree/commands/generic-commands.tsx
  src/packages/frontend/i18n/common.ts
  src/packages/frontend/i18n/trans/ar_EG.json
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/hi_IN.json
  src/packages/frontend/i18n/trans/hu_HU.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
  src/packages/frontend/misc/render-i18n.ts
  src/packages/frontend/notifications/notification-nav.tsx
  src/packages/frontend/notifications/notification-no-mentions.tsx
  src/packages/frontend/notifications/notification-page.tsx
  src/packages/frontend/project/named-server-panel.tsx
  src/packages/frontend/project/start-button.tsx
  src/packages/frontend/projects/projects-nav.tsx
  src/packages/frontend/projects/util.ts
  src/packages/util/compute-states.ts
Labels: PR-needs review

#7884 frontend/i18n: project servers, file creation buttons, ...
  src/packages/frontend/i18n/trans/ar_EG.json
  src/packages/frontend/i18n/trans/de_DE.json
  src/packages/frontend/i18n/trans/es_ES.json
  src/packages/frontend/i18n/trans/fr_FR.json
  src/packages/frontend/i18n/trans/he_IL.json
  src/packages/frontend/i18n/trans/hi_IN.json
  src/packages/frontend/i18n/trans/hu_HU.json
  src/packages/frontend/i18n/trans/it_IT.json
  src/packages/frontend/i18n/trans/ja_JP.json
  src/packages/frontend/i18n/trans/ko_KR.json
  src/packages/frontend/i18n/trans/pl_PL.json
  src/packages/frontend/i18n/trans/pt_PT.json
  src/packages/frontend/i18n/trans/ru_RU.json
  src/packages/frontend/i18n/trans/tr_TR.json
  src/packages/frontend/i18n/trans/zh_CN.json
  src/packages/frontend/project/explorer/action-bar.tsx
  src/packages/frontend/project/explorer/misc-side-buttons.tsx
  src/packages/frontend/project/named-server-panel.tsx
  src/packages/frontend/project/new/file-type-selector.tsx
  src/packages/frontend/project/new/new-file-dropdown.tsx
  src/packages/frontend/project/page/flyouts/header.tsx
  src/packages/frontend/project/page/flyouts/new.tsx
  src/packages/frontend/project/servers/project-servers.tsx
Labels: PR-needs review

#7890 frontend: tag ubuntu2204_2024-08-01 as a new image
  src/packages/util/compute-images.ts
Labels: E-easy, PR-needs review
