Repository sagemathinc/cocalc, pull requests merged in 2024-02, with the labels that each got.

#7232 frontend/x11: fix fallout of using our own reuseInFlight
  src/packages/frontend/course/configuration/actions.ts
  src/packages/frontend/course/students/actions.ts
  src/packages/frontend/frame-editors/code-editor/actions.ts
  src/packages/frontend/frame-editors/x11-editor/actions.ts
  src/packages/frontend/frame-editors/x11-editor/xpra-client.ts
  src/packages/frontend/frame-editors/x11-editor/xpra-server.ts
  src/packages/project/lean/lean.ts
  src/packages/project/sync/project-status.ts
Labels: PR-needs review

#7231 next/compute-infographic: change to "neural networks"
  src/packages/next/public/features/cocalc-compute-infographic-20231124.jpg
Labels: PR-needs review

#7233 npm updates 20240202
  src/packages/hub/package.json
  src/packages/pnpm-lock.yaml
  src/packages/server/package.json
  src/packages/server/support/create-ticket.ts
  src/packages/server/support/get-tickets.ts
  src/packages/server/support/zendesk-client.test.ts
  src/packages/server/support/zendesk-client.ts
  src/packages/util/db-schema/site-settings-extras.ts
Labels: PR-needs review

#7234 frontend/latex/pdf: fix horizontal dragging
  src/packages/frontend/frame-editors/latex-editor/pdfjs.tsx
Labels: PR-needs review

#7238 Chore/7213: Inline login component
  src/packages/next/components/auth/fragments/auth-page-container.tsx
  src/packages/next/components/auth/in-place-sign-in-or-up.tsx
  src/packages/next/components/auth/password-reset.tsx
  src/packages/next/components/auth/redeem-password-reset.tsx
  src/packages/next/components/auth/redeem-verify-email.tsx
  src/packages/next/components/auth/shared.ts
  src/packages/next/components/auth/sign-in.tsx
  src/packages/next/components/auth/sign-up.tsx
  src/packages/next/components/auth/try.tsx
  src/packages/next/components/landing/available-tools.tsx
  src/packages/next/components/landing/cocalc-com-features.tsx
  src/packages/next/components/landing/compute-servers.tsx
  src/packages/next/components/landing/constants.ts
  src/packages/next/components/landing/content.tsx
  src/packages/next/components/landing/header.tsx
  src/packages/next/components/landing/info.tsx
  src/packages/next/components/landing/sub-nav.tsx
  src/packages/next/components/misc/integer-slider.tsx
  src/packages/next/components/openai/chatgpt-help.tsx
  src/packages/next/components/store/cost-info-bar.tsx
  src/packages/next/components/store/run-limit.tsx
  src/packages/next/components/store/sign-in-to-purchase.tsx
  src/packages/next/components/store/store-inplace-signup.tsx
  src/packages/next/components/store/vouchers.tsx
  src/packages/next/components/vouchers/help.tsx
  src/packages/next/pages/auth/password-reset-done.tsx
  src/packages/next/pages/auth/password-reset.tsx
  src/packages/next/pages/auth/password-reset/[id].tsx
  src/packages/next/pages/auth/sign-in.tsx
  src/packages/next/pages/features/ai.tsx
  src/packages/next/pages/features/api.tsx
  src/packages/next/pages/features/compute-server.tsx
  src/packages/next/pages/features/julia.tsx
  src/packages/next/pages/features/jupyter-notebook.tsx
  src/packages/next/pages/features/latex-editor.tsx
  src/packages/next/pages/features/linux.tsx
  src/packages/next/pages/features/octave.tsx
  src/packages/next/pages/features/python.tsx
  src/packages/next/pages/features/r-statistical-software.tsx
  src/packages/next/pages/features/sage.tsx
  src/packages/next/pages/features/slides.tsx
  src/packages/next/pages/features/teaching.tsx
  src/packages/next/pages/features/terminal.tsx
  src/packages/next/pages/features/whiteboard.tsx
  src/packages/next/pages/features/x11.tsx
  src/packages/next/pages/index.tsx
  src/packages/next/pages/redeem.tsx
  src/packages/next/pages/vouchers/admin.tsx
  src/packages/next/pages/vouchers/created.tsx
  src/packages/next/pages/vouchers/redeemed.tsx
Labels: PR-needs work

#7246 frontend/flyout/new: different algorithm
  src/packages/frontend/project/new/file-type-selector.tsx
  src/packages/frontend/project/new/new-file-dropdown.tsx
  src/packages/frontend/project/page/flyouts/new.tsx
  src/packages/frontend/project/utils.ts
Labels: PR-needs review

#7247 frontend/left vertical bar: always show labels....
  src/packages/frontend/project/page/file-tab.tsx
  src/packages/frontend/project/page/tabs.tsx
Labels: PR-needs review

#7253 server/zendesk: fix name+email
  src/packages/server/support/create-ticket.ts
Labels: PR-needs review

#7256 frontend: remove 6 year old dead tests
  src/packages/frontend/account/test/preferences.ts
  src/packages/frontend/course/test/mocha.opts
  src/packages/frontend/course/test/project-upgrades.coffee
  src/packages/frontend/frame-editors/code-editor/test/actions.ts
  src/packages/frontend/frame-editors/code-editor/test/basic.ts
  src/packages/frontend/frame-editors/code-editor/test/frame.ts
  src/packages/frontend/frame-editors/generic/mocha-tests/misc.ts
  src/packages/frontend/frame-editors/generic/mocha-tests/mocha.opts
  src/packages/frontend/frame-editors/generic/mocha-tests/run
  src/packages/frontend/frame-editors/generic/test/init.ts
  src/packages/frontend/frame-editors/generic/test/util.ts
  src/packages/frontend/frame-editors/markdown-editor/test/basic.ts
  src/packages/frontend/frame-editors/markdown-editor/test/math.ts
  src/packages/frontend/package.json
  src/packages/pnpm-lock.yaml
Labels: PR-needs review

#7266 frontend/latex+md: AI text -> formula button
  src/packages/frontend/codemirror/extensions/ai-formula.tsx
  src/packages/frontend/codemirror/extensions/edit-selection.ts
  src/packages/frontend/codemirror/extensions/insert-image.tsx
  src/packages/frontend/frame-editors/code-editor/actions.ts
  src/packages/frontend/frame-editors/frame-tree/commands/format-commands.tsx
  src/packages/frontend/frame-editors/generic/codemirror-plugins.ts
  src/packages/frontend/frame-editors/latex-editor/editor.ts
Labels: PR-needs review

#7259 npm updates 2024-02-08
  src/packages/cdn/package-lock.json
  src/packages/cdn/package.json
  src/packages/frontend/frame-editors/latex-editor/pdfjs-annotation.tsx
  src/packages/frontend/frame-editors/latex-editor/pdfjs-canvas-page.tsx
  src/packages/frontend/frame-editors/latex-editor/pdfjs-doc-cache.ts
  src/packages/frontend/frame-editors/latex-editor/pdfjs-page.tsx
  src/packages/frontend/frame-editors/latex-editor/pdfjs.tsx
  src/packages/frontend/package.json
  src/packages/hub/package.json
  src/packages/pnpm-lock.yaml
  src/packages/project/browser-websocket/server.ts
  src/packages/project/package.json
  src/packages/server/auth/sso/extra-strategies.ts
  src/packages/server/auth/sso/types.ts
  src/packages/server/hub/auth.ts
  src/packages/server/package.json
  src/packages/static/package.json
  src/packages/static/src/webpack.config.ts
  src/packages/sync-client/lib/connect-to-project.ts
  src/packages/sync-client/package.json
  src/packages/sync-client/scratch/primus.ts
  src/packages/terminal/package.json
Labels: PR-needs review

#7271 Ai formula followups
  src/packages/frontend/codemirror/extensions/ai-formula.tsx
  src/packages/frontend/codemirror/extensions/edit-selection.ts
  src/packages/next/pages/features/latex-editor.tsx
  src/packages/next/public/features/latex-ai-formula.png
Labels: PR-needs review

#7274 Added support for self-signed SSL configuration with Postgres.
  src/packages/backend/data.test.ts
  src/packages/backend/data.ts
  src/packages/backend/jest.config.js
  src/packages/backend/package.json
  src/packages/database/pool/pool.ts
  src/packages/database/postgres-base.coffee
Labels: PR-work in progress

#7281 sagews/help me fix: use current llm
  src/packages/frontend/sagews/chatgpt.ts
Labels: PR-needs review

#7273 server: update OpenAI API from 3 -> 4
  src/packages/pnpm-lock.yaml
  src/packages/server/llm/call-chatgpt.ts
  src/packages/server/llm/client.ts
  src/packages/server/llm/embeddings.ts
  src/packages/server/llm/index.ts
  src/packages/server/package.json
  src/packages/util/db-schema/openai.ts
Labels: PR-needs review

#7288 npm: update pnpm in src root dir
  src/package.json
Labels: PR-needs review

#7277 Reintroduce auth component changes
  src/packages/next/components/auth/fragments/auth-page-container.tsx
  src/packages/next/components/auth/in-place-sign-in-or-up.tsx
  src/packages/next/components/auth/password-reset.tsx
  src/packages/next/components/auth/redeem-password-reset.tsx
  src/packages/next/components/auth/redeem-verify-email.tsx
  src/packages/next/components/auth/shared.ts
  src/packages/next/components/auth/sign-in.tsx
  src/packages/next/components/auth/sign-up.tsx
  src/packages/next/components/auth/try.tsx
  src/packages/next/components/landing/available-tools.tsx
  src/packages/next/components/landing/cocalc-com-features.tsx
  src/packages/next/components/landing/compute-servers.tsx
  src/packages/next/components/landing/constants.ts
  src/packages/next/components/landing/content.tsx
  src/packages/next/components/landing/info.tsx
  src/packages/next/components/landing/sub-nav.tsx
  src/packages/next/components/misc/integer-slider.tsx
  src/packages/next/components/openai/chatgpt-help.tsx
  src/packages/next/components/store/cost-info-bar.tsx
  src/packages/next/components/store/menu.tsx
  src/packages/next/components/store/run-limit.tsx
  src/packages/next/components/store/sign-in-to-purchase.tsx
  src/packages/next/components/store/store-inplace-signup.tsx
  src/packages/next/pages/auth/password-reset-done.tsx
  src/packages/next/pages/auth/password-reset.tsx
  src/packages/next/pages/auth/password-reset/[id].tsx
  src/packages/next/pages/auth/sign-in.tsx
  src/packages/next/pages/features/ai.tsx
  src/packages/next/pages/features/api.tsx
  src/packages/next/pages/features/compute-server.tsx
  src/packages/next/pages/features/julia.tsx
  src/packages/next/pages/features/jupyter-notebook.tsx
  src/packages/next/pages/features/latex-editor.tsx
  src/packages/next/pages/features/linux.tsx
  src/packages/next/pages/features/octave.tsx
  src/packages/next/pages/features/python.tsx
  src/packages/next/pages/features/r-statistical-software.tsx
  src/packages/next/pages/features/sage.tsx
  src/packages/next/pages/features/slides.tsx
  src/packages/next/pages/features/teaching.tsx
  src/packages/next/pages/features/terminal.tsx
  src/packages/next/pages/features/whiteboard.tsx
  src/packages/next/pages/features/x11.tsx
  src/packages/next/pages/index.tsx
  src/packages/next/pages/redeem.tsx
  src/packages/next/pages/vouchers/admin.tsx
  src/packages/next/pages/vouchers/created.tsx
  src/packages/next/pages/vouchers/index.tsx
  src/packages/next/pages/vouchers/redeemed.tsx
  src/packages/next/public/features/cocalc-compute-infographic-20231124.jpg
Labels: PR-needs review

#7291 store/dedicated/vm: add note about startup delay
  src/packages/next/components/store/dedicated.tsx
Labels: PR-needs review
